// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -package=clipboard -destination=reader_mocks_test.go -source=types.go ClipboardReader
//

package clipboard

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClipboardReader is a mock of ClipboardReader interface.
type MockClipboardReader struct {
	ctrl     *gomock.Controller
	recorder *MockClipboardReaderMockRecorder
	isgomock struct{}
}

// MockClipboardReaderMockRecorder is the mock recorder for MockClipboardReader.
type MockClipboardReaderMockRecorder struct {
	mock *MockClipboardReader
}

// NewMockClipboardReader creates a new mock instance.
func NewMockClipboardReader(ctrl *gomock.Controller) *MockClipboardReader {
	mock := &MockClipboardReader{ctrl: ctrl}
	mock.recorder = &MockClipboardReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClipboardReader) EXPECT() *MockClipboardReaderMockRecorder {
	return m.recorder
}

// Snapshot mocks base method.
func (m *MockClipboardReader) Snapshot(ctx context.Context) (Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", ctx)
	ret0, _ := ret[0].(Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockClipboardReaderMockRecorder) Snapshot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockClipboardReader)(nil).Snapshot), ctx)
}
