// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -package=clipboard -destination=runner_mocks_test.go -source=runner.go
//

package clipboard

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCopyRunner is a mock of CopyRunner interface.
type MockCopyRunner struct {
	ctrl     *gomock.Controller
	recorder *MockCopyRunnerMockRecorder
	isgomock struct{}
}

// MockCopyRunnerMockRecorder is the mock recorder for MockCopyRunner.
type MockCopyRunnerMockRecorder struct {
	mock *MockCopyRunner
}

// NewMockCopyRunner creates a new mock instance.
func NewMockCopyRunner(ctrl *gomock.Controller) *MockCopyRunner {
	mock := &MockCopyRunner{ctrl: ctrl}
	mock.recorder = &MockCopyRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCopyRunner) EXPECT() *MockCopyRunnerMockRecorder {
	return m.recorder
}

// LookPath mocks base method.
func (m *MockCopyRunner) LookPath(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookPath", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookPath indicates an expected call of LookPath.
func (mr *MockCopyRunnerMockRecorder) LookPath(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookPath", reflect.TypeOf((*MockCopyRunner)(nil).LookPath), name)
}

// Run mocks base method.
func (m *MockCopyRunner) Run(ctx context.Context, name string, args []string, stdin []byte, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, name, args, stdin, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockCopyRunnerMockRecorder) Run(ctx, name, args, stdin, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCopyRunner)(nil).Run), ctx, name, args, stdin, timeout)
}

// MockPasteRunner is a mock of PasteRunner interface.
type MockPasteRunner struct {
	ctrl     *gomock.Controller
	recorder *MockPasteRunnerMockRecorder
	isgomock struct{}
}

// MockPasteRunnerMockRecorder is the mock recorder for MockPasteRunner.
type MockPasteRunnerMockRecorder struct {
	mock *MockPasteRunner
}

// NewMockPasteRunner creates a new mock instance.
func NewMockPasteRunner(ctrl *gomock.Controller) *MockPasteRunner {
	mock := &MockPasteRunner{ctrl: ctrl}
	mock.recorder = &MockPasteRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasteRunner) EXPECT() *MockPasteRunnerMockRecorder {
	return m.recorder
}

// LookPath mocks base method.
func (m *MockPasteRunner) LookPath(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookPath", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookPath indicates an expected call of LookPath.
func (mr *MockPasteRunnerMockRecorder) LookPath(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookPath", reflect.TypeOf((*MockPasteRunner)(nil).LookPath), name)
}

// Run mocks base method.
func (m *MockPasteRunner) Run(ctx context.Context, name string, args []string, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, name, args, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockPasteRunnerMockRecorder) Run(ctx, name, args, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockPasteRunner)(nil).Run), ctx, name, args, timeout)
}
