// Keyboard subsystem of a2textd.
//
// The daemon owns both halves of the kernel keyboard pipeline that
// require the "input" group: reading physical key events from
// /dev/input/event* (evdev) and writing synthetic key events to
// /dev/uinput. This service surfaces both halves to UI clients over
// the loopback gRPC channel (mTLS-pinned), plus a non-hotkey trigger
// (StartCycle) that lets the UI begin a recording cycle from the
// tray menu or a settings button.
//
// Read side: StreamHotkeyEvents pushes semantic transitions of the
// daemon-configured hotkey. The daemon translates physical edges
// using its HOLD/TOGGLE config so the UI sees ready-to-use kinds.
//
// Write side: Inject hands the daemon a transcript and lets the
// daemon decide, from its config-driven output policy, what to do
// with it. The daemon may press Ctrl+V on its persistent uinput
// keyboard (INJECT_MODE_PASTE — primary flow), report that the
// active policy is clipboard-only and that the UI must complete the
// delivery itself (INJECT_MODE_CLIPBOARD), or — once implemented —
// type the payload key-by-key (INJECT_MODE_TYPE, wire-reserved but
// not yet honoured).
//
// Trigger side: StartCycle is the UI-initiated equivalent of a
// physical hotkey press. It begins a recording cycle on the daemon
// and returns the inject_token the UI will need at paste time.
//
// Out of scope: clipboard writes (wl-copy, xclip, pbcopy) and the
// display-socket autopaste backends (wtype, xdotool) do NOT go through
// this service. The UI has direct access to the user's display socket
// and invokes those tools locally.
//
// Race-guarding (verifying the clipboard still contains the expected
// transcript before Ctrl+V is injected) is the UI's responsibility
// because the UI owns the clipboard view. The daemon trusts the
// request and presses keys.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.1
// source: a2text/v1/keyboard.proto

package a2textv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyboardService_StreamHotkeyEvents_FullMethodName = "/a2text.v1.KeyboardService/StreamHotkeyEvents"
	KeyboardService_Inject_FullMethodName             = "/a2text.v1.KeyboardService/Inject"
	KeyboardService_StartCycle_FullMethodName         = "/a2text.v1.KeyboardService/StartCycle"
)

// KeyboardServiceClient is the client API for KeyboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KeyboardService merges hotkey-read and uinput-write into one wire
// surface. Every RPC is invoked under mTLS.
type KeyboardServiceClient interface {
	// StreamHotkeyEvents subscribes the caller to semantic hotkey events
	// produced from the daemon-owned evdev binding. The daemon reads its
	// config to decide how to translate physical key transitions into
	// events:
	//   - mode = HOLD   → emits PRESS on key-down, RELEASE on key-up.
	//   - mode = TOGGLE → emits TOGGLE on key-down; key-up is suppressed.
	//
	// The stream is framed: the very first frame is always an
	// InitialState that snapshots the daemon's view at the moment of
	// subscribe (current mode and whether the daemon already considers
	// itself recording, e.g. because the user was holding the hotkey
	// when the UI connected). Every subsequent frame carries a single
	// HotkeyEvent. The server keeps the stream open until the client
	// cancels or the daemon shuts down. Events are best-effort: slow
	// consumers may see dropped HotkeyEvent frames (lossy ring buffer
	// policy). The InitialState frame is never dropped — the daemon
	// delays acknowledging the stream until it has been pushed.
	StreamHotkeyEvents(ctx context.Context, in *StreamHotkeyEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HotkeyStreamFrame], error)
	// Inject hands the daemon a transcript and asks it to act on it
	// according to the active output policy. The request must carry
	// the inject_token issued by the cycle that produced the
	// transcript (via HotkeyEvent or RecordingService.StartCycle);
	// the daemon rejects requests with an empty, unknown, expired, or
	// already-consumed token. The same token on retry yields the
	// cached response without performing a second uinput action.
	//
	// The daemon may resolve the call to:
	//   - INJECT_MODE_PASTE     — synthesise a Ctrl+V chord on the
	//     uinput keyboard. The UI must have written the transcript to
	//     the clipboard beforehand. This is the primary supported flow.
	//   - INJECT_MODE_CLIPBOARD — clipboard-only output policy; the
	//     daemon performed no uinput action. The UI is fully
	//     responsible for delivering the transcript via its local
	//     clipboard helper.
	//   - INJECT_MODE_TYPE      — wire-reserved future fallback;
	//     currently rejected by the daemon.
	//
	// The mode the daemon resolved to is returned in
	// InjectResponse.mode so the UI can log it and confirm the daemon's
	// read of the policy. Expected gRPC error codes: INVALID_ARGUMENT
	// (empty text or empty token), PERMISSION_DENIED (unknown,
	// expired, or consumed token), FAILED_PRECONDITION (uinput device
	// unavailable).
	Inject(ctx context.Context, in *InjectRequest, opts ...grpc.CallOption) (*InjectResponse, error)
	// StartCycle begins a new recording cycle on behalf of the caller
	// and returns the inject_token the caller will need at paste time.
	// The daemon enters the same state machine it would on a physical
	// hotkey press: starts audio capture, mints a fresh token, and
	// emits a HotkeyEvent on every active StreamHotkeyEvents
	// subscription so observer UIs see the cycle begin. The token
	// expires after a daemon-side TTL if Inject is never called.
	//
	// Stop is not exposed: cycles end on their own terms (silence
	// gate, max-duration timeout, or a physical hotkey press while a
	// UI-initiated cycle is in flight). Adding a stop RPC later is
	// non-breaking.
	//
	// Expected gRPC error codes: FAILED_PRECONDITION (a cycle is
	// already in flight), RESOURCE_EXHAUSTED (audio device not
	// available).
	StartCycle(ctx context.Context, in *StartCycleRequest, opts ...grpc.CallOption) (*StartCycleResponse, error)
}

type keyboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyboardServiceClient(cc grpc.ClientConnInterface) KeyboardServiceClient {
	return &keyboardServiceClient{cc}
}

func (c *keyboardServiceClient) StreamHotkeyEvents(ctx context.Context, in *StreamHotkeyEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HotkeyStreamFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KeyboardService_ServiceDesc.Streams[0], KeyboardService_StreamHotkeyEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamHotkeyEventsRequest, HotkeyStreamFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeyboardService_StreamHotkeyEventsClient = grpc.ServerStreamingClient[HotkeyStreamFrame]

func (c *keyboardServiceClient) Inject(ctx context.Context, in *InjectRequest, opts ...grpc.CallOption) (*InjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectResponse)
	err := c.cc.Invoke(ctx, KeyboardService_Inject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyboardServiceClient) StartCycle(ctx context.Context, in *StartCycleRequest, opts ...grpc.CallOption) (*StartCycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartCycleResponse)
	err := c.cc.Invoke(ctx, KeyboardService_StartCycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyboardServiceServer is the server API for KeyboardService service.
// All implementations must embed UnimplementedKeyboardServiceServer
// for forward compatibility.
//
// KeyboardService merges hotkey-read and uinput-write into one wire
// surface. Every RPC is invoked under mTLS.
type KeyboardServiceServer interface {
	// StreamHotkeyEvents subscribes the caller to semantic hotkey events
	// produced from the daemon-owned evdev binding. The daemon reads its
	// config to decide how to translate physical key transitions into
	// events:
	//   - mode = HOLD   → emits PRESS on key-down, RELEASE on key-up.
	//   - mode = TOGGLE → emits TOGGLE on key-down; key-up is suppressed.
	//
	// The stream is framed: the very first frame is always an
	// InitialState that snapshots the daemon's view at the moment of
	// subscribe (current mode and whether the daemon already considers
	// itself recording, e.g. because the user was holding the hotkey
	// when the UI connected). Every subsequent frame carries a single
	// HotkeyEvent. The server keeps the stream open until the client
	// cancels or the daemon shuts down. Events are best-effort: slow
	// consumers may see dropped HotkeyEvent frames (lossy ring buffer
	// policy). The InitialState frame is never dropped — the daemon
	// delays acknowledging the stream until it has been pushed.
	StreamHotkeyEvents(*StreamHotkeyEventsRequest, grpc.ServerStreamingServer[HotkeyStreamFrame]) error
	// Inject hands the daemon a transcript and asks it to act on it
	// according to the active output policy. The request must carry
	// the inject_token issued by the cycle that produced the
	// transcript (via HotkeyEvent or RecordingService.StartCycle);
	// the daemon rejects requests with an empty, unknown, expired, or
	// already-consumed token. The same token on retry yields the
	// cached response without performing a second uinput action.
	//
	// The daemon may resolve the call to:
	//   - INJECT_MODE_PASTE     — synthesise a Ctrl+V chord on the
	//     uinput keyboard. The UI must have written the transcript to
	//     the clipboard beforehand. This is the primary supported flow.
	//   - INJECT_MODE_CLIPBOARD — clipboard-only output policy; the
	//     daemon performed no uinput action. The UI is fully
	//     responsible for delivering the transcript via its local
	//     clipboard helper.
	//   - INJECT_MODE_TYPE      — wire-reserved future fallback;
	//     currently rejected by the daemon.
	//
	// The mode the daemon resolved to is returned in
	// InjectResponse.mode so the UI can log it and confirm the daemon's
	// read of the policy. Expected gRPC error codes: INVALID_ARGUMENT
	// (empty text or empty token), PERMISSION_DENIED (unknown,
	// expired, or consumed token), FAILED_PRECONDITION (uinput device
	// unavailable).
	Inject(context.Context, *InjectRequest) (*InjectResponse, error)
	// StartCycle begins a new recording cycle on behalf of the caller
	// and returns the inject_token the caller will need at paste time.
	// The daemon enters the same state machine it would on a physical
	// hotkey press: starts audio capture, mints a fresh token, and
	// emits a HotkeyEvent on every active StreamHotkeyEvents
	// subscription so observer UIs see the cycle begin. The token
	// expires after a daemon-side TTL if Inject is never called.
	//
	// Stop is not exposed: cycles end on their own terms (silence
	// gate, max-duration timeout, or a physical hotkey press while a
	// UI-initiated cycle is in flight). Adding a stop RPC later is
	// non-breaking.
	//
	// Expected gRPC error codes: FAILED_PRECONDITION (a cycle is
	// already in flight), RESOURCE_EXHAUSTED (audio device not
	// available).
	StartCycle(context.Context, *StartCycleRequest) (*StartCycleResponse, error)
	mustEmbedUnimplementedKeyboardServiceServer()
}

// UnimplementedKeyboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyboardServiceServer struct{}

func (UnimplementedKeyboardServiceServer) StreamHotkeyEvents(*StreamHotkeyEventsRequest, grpc.ServerStreamingServer[HotkeyStreamFrame]) error {
	return status.Error(codes.Unimplemented, "method StreamHotkeyEvents not implemented")
}
func (UnimplementedKeyboardServiceServer) Inject(context.Context, *InjectRequest) (*InjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Inject not implemented")
}
func (UnimplementedKeyboardServiceServer) StartCycle(context.Context, *StartCycleRequest) (*StartCycleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartCycle not implemented")
}
func (UnimplementedKeyboardServiceServer) mustEmbedUnimplementedKeyboardServiceServer() {}
func (UnimplementedKeyboardServiceServer) testEmbeddedByValue()                         {}

// UnsafeKeyboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyboardServiceServer will
// result in compilation errors.
type UnsafeKeyboardServiceServer interface {
	mustEmbedUnimplementedKeyboardServiceServer()
}

func RegisterKeyboardServiceServer(s grpc.ServiceRegistrar, srv KeyboardServiceServer) {
	// If the following call panics, it indicates UnimplementedKeyboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyboardService_ServiceDesc, srv)
}

func _KeyboardService_StreamHotkeyEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamHotkeyEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeyboardServiceServer).StreamHotkeyEvents(m, &grpc.GenericServerStream[StreamHotkeyEventsRequest, HotkeyStreamFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeyboardService_StreamHotkeyEventsServer = grpc.ServerStreamingServer[HotkeyStreamFrame]

func _KeyboardService_Inject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyboardServiceServer).Inject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyboardService_Inject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyboardServiceServer).Inject(ctx, req.(*InjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyboardService_StartCycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyboardServiceServer).StartCycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyboardService_StartCycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyboardServiceServer).StartCycle(ctx, req.(*StartCycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyboardService_ServiceDesc is the grpc.ServiceDesc for KeyboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "a2text.v1.KeyboardService",
	HandlerType: (*KeyboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Inject",
			Handler:    _KeyboardService_Inject_Handler,
		},
		{
			MethodName: "StartCycle",
			Handler:    _KeyboardService_StartCycle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHotkeyEvents",
			Handler:       _KeyboardService_StreamHotkeyEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "a2text/v1/keyboard.proto",
}
