// Keyboard subsystem of a2textd.
//
// The daemon owns both halves of the kernel keyboard pipeline that
// require the "input" group: reading physical key events from
// /dev/input/event* (evdev) and writing synthetic key events to
// /dev/uinput. This service surfaces both halves to UI clients over
// the loopback gRPC channel (mTLS-pinned), plus a non-hotkey trigger
// (StartCycle) that lets the UI begin a recording cycle from the
// tray menu or a settings button.
//
// Read side: StreamHotkeyEvents pushes semantic transitions of the
// daemon-configured hotkey. The daemon translates physical edges
// using its HOLD/TOGGLE config so the UI sees ready-to-use kinds.
//
// Write side: Inject hands the daemon a transcript and lets the
// daemon decide, from its config-driven output policy, what to do
// with it. The daemon may press Ctrl+V on its persistent uinput
// keyboard (INJECT_MODE_PASTE — primary flow), report that the
// active policy is clipboard-only and that the UI must complete the
// delivery itself (INJECT_MODE_CLIPBOARD), or — once implemented —
// type the payload key-by-key (INJECT_MODE_TYPE, wire-reserved but
// not yet honoured).
//
// Trigger side: StartCycle is the UI-initiated equivalent of a
// physical hotkey press. It begins a recording cycle on the daemon
// and returns the inject_token the UI will need at paste time.
//
// Out of scope: clipboard writes (wl-copy, xclip, pbcopy) and the
// display-socket autopaste backends (wtype, xdotool) do NOT go through
// this service. The UI has direct access to the user's display socket
// and invokes those tools locally.
//
// Race-guarding (verifying the clipboard still contains the expected
// transcript before Ctrl+V is injected) is the UI's responsibility
// because the UI owns the clipboard view. The daemon trusts the
// request and presses keys.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: a2text/v1/keyboard.proto

package a2textv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HotkeyState enumerates the daemon-side recording state that the UI
// must mirror on the tray badge / status indicator. Used only in
// InitialState; subsequent transitions are surfaced via HotkeyEvent.
type HotkeyState int32

const (
	// sentinel for the proto3 default-zero slot. The daemon never
	// emits this value; clients that receive it should treat the
	// frame as malformed (log + drop). Reserved so that the zero
	// value is unambiguously an error and not a legitimate state.
	HotkeyState_HOTKEY_STATE_INVALID HotkeyState = 0
	// no recording is in flight.
	HotkeyState_HOTKEY_STATE_IDLE HotkeyState = 1
	// the daemon is currently recording (HOLD with the key still down,
	// or TOGGLE that has not yet been turned off).
	HotkeyState_HOTKEY_STATE_RECORDING HotkeyState = 2
)

// Enum value maps for HotkeyState.
var (
	HotkeyState_name = map[int32]string{
		0: "HOTKEY_STATE_INVALID",
		1: "HOTKEY_STATE_IDLE",
		2: "HOTKEY_STATE_RECORDING",
	}
	HotkeyState_value = map[string]int32{
		"HOTKEY_STATE_INVALID":   0,
		"HOTKEY_STATE_IDLE":      1,
		"HOTKEY_STATE_RECORDING": 2,
	}
)

func (x HotkeyState) Enum() *HotkeyState {
	p := new(HotkeyState)
	*p = x
	return p
}

func (x HotkeyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HotkeyState) Descriptor() protoreflect.EnumDescriptor {
	return file_a2text_v1_keyboard_proto_enumTypes[0].Descriptor()
}

func (HotkeyState) Type() protoreflect.EnumType {
	return &file_a2text_v1_keyboard_proto_enumTypes[0]
}

func (x HotkeyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HotkeyState.Descriptor instead.
func (HotkeyState) EnumDescriptor() ([]byte, []int) {
	return file_a2text_v1_keyboard_proto_rawDescGZIP(), []int{0}
}

// HotkeyMode mirrors config.hotkey.mode and tells the UI how the
// daemon interprets the event stream. Used only in InitialState; the
// per-event HotkeyEventKind is self-describing for subsequent frames.
type HotkeyMode int32

const (
	// sentinel for the proto3 default-zero slot. The daemon never
	// emits this value; clients that receive it should treat the
	// frame as malformed (log + drop). Reserved so that the zero
	// value is unambiguously an error and not a legitimate mode.
	HotkeyMode_HOTKEY_MODE_INVALID HotkeyMode = 0
	// press starts recording, release stops it (push-to-talk).
	HotkeyMode_HOTKEY_MODE_HOLD HotkeyMode = 1
	// each press toggles recording on or off; release events are
	// suppressed by the daemon.
	HotkeyMode_HOTKEY_MODE_TOGGLE HotkeyMode = 2
)

// Enum value maps for HotkeyMode.
var (
	HotkeyMode_name = map[int32]string{
		0: "HOTKEY_MODE_INVALID",
		1: "HOTKEY_MODE_HOLD",
		2: "HOTKEY_MODE_TOGGLE",
	}
	HotkeyMode_value = map[string]int32{
		"HOTKEY_MODE_INVALID": 0,
		"HOTKEY_MODE_HOLD":    1,
		"HOTKEY_MODE_TOGGLE":  2,
	}
)

func (x HotkeyMode) Enum() *HotkeyMode {
	p := new(HotkeyMode)
	*p = x
	return p
}

func (x HotkeyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HotkeyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_a2text_v1_keyboard_proto_enumTypes[1].Descriptor()
}

func (HotkeyMode) Type() protoreflect.EnumType {
	return &file_a2text_v1_keyboard_proto_enumTypes[1]
}

func (x HotkeyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HotkeyMode.Descriptor instead.
func (HotkeyMode) EnumDescriptor() ([]byte, []int) {
	return file_a2text_v1_keyboard_proto_rawDescGZIP(), []int{1}
}

// HotkeyEventKind enumerates the semantic kinds the daemon emits.
// Which kind appears in the stream depends on the active mode:
//   - HOLD   produces PRESS (key-down) and RELEASE (key-up).
//   - TOGGLE produces TOGGLE on each key-down; key-up is suppressed.
type HotkeyEventKind int32

const (
	// sentinel for the proto3 default-zero slot. The daemon never
	// emits this value; clients that receive it should treat the
	// frame as malformed (log + drop). Reserved so that the zero
	// value is unambiguously an error and not a legitimate kind.
	HotkeyEventKind_HOTKEY_EVENT_KIND_INVALID HotkeyEventKind = 0
	// the configured hotkey just went down (HOLD mode only).
	HotkeyEventKind_HOTKEY_EVENT_KIND_PRESS HotkeyEventKind = 1
	// the configured hotkey just came up (HOLD mode only).
	HotkeyEventKind_HOTKEY_EVENT_KIND_RELEASE HotkeyEventKind = 2
	// the configured hotkey was tapped once and the daemon flipped the
	// recording state (TOGGLE mode only).
	HotkeyEventKind_HOTKEY_EVENT_KIND_TOGGLE HotkeyEventKind = 3
)

// Enum value maps for HotkeyEventKind.
var (
	HotkeyEventKind_name = map[int32]string{
		0: "HOTKEY_EVENT_KIND_INVALID",
		1: "HOTKEY_EVENT_KIND_PRESS",
		2: "HOTKEY_EVENT_KIND_RELEASE",
		3: "HOTKEY_EVENT_KIND_TOGGLE",
	}
	HotkeyEventKind_value = map[string]int32{
		"HOTKEY_EVENT_KIND_INVALID": 0,
		"HOTKEY_EVENT_KIND_PRESS":   1,
		"HOTKEY_EVENT_KIND_RELEASE": 2,
		"HOTKEY_EVENT_KIND_TOGGLE":  3,
	}
)

func (x HotkeyEventKind) Enum() *HotkeyEventKind {
	p := new(HotkeyEventKind)
	*p = x
	return p
}

func (x HotkeyEventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HotkeyEventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_a2text_v1_keyboard_proto_enumTypes[2].Descriptor()
}

func (HotkeyEventKind) Type() protoreflect.EnumType {
	return &file_a2text_v1_keyboard_proto_enumTypes[2]
}

func (x HotkeyEventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HotkeyEventKind.Descriptor instead.
func (HotkeyEventKind) EnumDescriptor() ([]byte, []int) {
	return file_a2text_v1_keyboard_proto_rawDescGZIP(), []int{2}
}

// InjectMode enumerates the delivery strategies the daemon may pick
// for an Inject call. The choice is made server-side from config; the
// caller never sets this on a request — it is only ever observed in
// InjectResponse.mode. Values are ordered from least to most
// invasive: clipboard-only (no uinput at all), chord (one Ctrl+V),
// per-character typing.
type InjectMode int32

const (
	// sentinel for the proto3 default-zero slot. The daemon never
	// emits this value; clients that receive it should treat the
	// response as malformed (log + drop). Reserved so that the zero
	// value is unambiguously an error and not a legitimate mode.
	InjectMode_INJECT_MODE_INVALID InjectMode = 0
	// daemon performed no uinput action because the active output
	// policy is clipboard-only. The transcript was intentionally not
	// pasted; the UI is fully responsible for delivering it (typically
	// by writing it to the user's clipboard via the local
	// wl-copy/xclip/pbcopy helper). Returned so the UI can confirm the
	// daemon's read of the policy and skip waiting for paste-side
	// side-effects.
	InjectMode_INJECT_MODE_CLIPBOARD InjectMode = 1
	// daemon pressed Ctrl+V on the uinput keyboard. The UI is assumed
	// to have written the transcript into the user's clipboard before
	// making the call (race-guard belongs in the UI). This is the
	// killer-feature flow of a2text and the primary supported mode.
	InjectMode_INJECT_MODE_PASTE InjectMode = 2
	// wire-reserved for a future per-character typing fallback (daemon
	// would press every codepoint of the request text on the uinput
	// keyboard, skipping unmappable codepoints with a warning). The
	// daemon does NOT honour this mode at this stage; clients should
	// not expect requests to ever resolve to it. The enum value is
	// kept so that adding the implementation later is non-breaking.
	InjectMode_INJECT_MODE_TYPE InjectMode = 3
)

// Enum value maps for InjectMode.
var (
	InjectMode_name = map[int32]string{
		0: "INJECT_MODE_INVALID",
		1: "INJECT_MODE_CLIPBOARD",
		2: "INJECT_MODE_PASTE",
		3: "INJECT_MODE_TYPE",
	}
	InjectMode_value = map[string]int32{
		"INJECT_MODE_INVALID":   0,
		"INJECT_MODE_CLIPBOARD": 1,
		"INJECT_MODE_PASTE":     2,
		"INJECT_MODE_TYPE":      3,
	}
)

func (x InjectMode) Enum() *InjectMode {
	p := new(InjectMode)
	*p = x
	return p
}

func (x InjectMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InjectMode) Descriptor() protoreflect.EnumDescriptor {
	return file_a2text_v1_keyboard_proto_enumTypes[3].Descriptor()
}

func (InjectMode) Type() protoreflect.EnumType {
	return &file_a2text_v1_keyboard_proto_enumTypes[3]
}

func (x InjectMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InjectMode.Descriptor instead.
func (InjectMode) EnumDescriptor() ([]byte, []int) {
	return file_a2text_v1_keyboard_proto_rawDescGZIP(), []int{3}
}

// StreamHotkeyEventsRequest opens a subscription to hotkey events.
// Empty by design; subscription scope is implicit (the single daemon-
// owned binding). Future filter fields will be added with new tag
// numbers when there is a real reason.
type StreamHotkeyEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamHotkeyEventsRequest) Reset() {
	*x = StreamHotkeyEventsRequest{}
	mi := &file_a2text_v1_keyboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHotkeyEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHotkeyEventsRequest) ProtoMessage() {}

func (x *StreamHotkeyEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2text_v1_keyboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHotkeyEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamHotkeyEventsRequest) Descriptor() ([]byte, []int) {
	return file_a2text_v1_keyboard_proto_rawDescGZIP(), []int{0}
}

// HotkeyStreamFrame is the wire frame the server-stream of
// StreamHotkeyEvents carries. The first frame in every subscription
// is always payload.initial_state; every subsequent frame carries
// payload.event.
type HotkeyStreamFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// exactly one of the two payload variants is set per frame.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*HotkeyStreamFrame_InitialState
	//	*HotkeyStreamFrame_Event
	Payload       isHotkeyStreamFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotkeyStreamFrame) Reset() {
	*x = HotkeyStreamFrame{}
	mi := &file_a2text_v1_keyboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotkeyStreamFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotkeyStreamFrame) ProtoMessage() {}

func (x *HotkeyStreamFrame) ProtoReflect() protoreflect.Message {
	mi := &file_a2text_v1_keyboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotkeyStreamFrame.ProtoReflect.Descriptor instead.
func (*HotkeyStreamFrame) Descriptor() ([]byte, []int) {
	return file_a2text_v1_keyboard_proto_rawDescGZIP(), []int{1}
}

func (x *HotkeyStreamFrame) GetPayload() isHotkeyStreamFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HotkeyStreamFrame) GetInitialState() *InitialState {
	if x != nil {
		if x, ok := x.Payload.(*HotkeyStreamFrame_InitialState); ok {
			return x.InitialState
		}
	}
	return nil
}

func (x *HotkeyStreamFrame) GetEvent() *HotkeyEvent {
	if x != nil {
		if x, ok := x.Payload.(*HotkeyStreamFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isHotkeyStreamFrame_Payload interface {
	isHotkeyStreamFrame_Payload()
}

type HotkeyStreamFrame_InitialState struct {
	// synchronous snapshot of the daemon's hotkey state at the
	// moment of subscribe. Sent exactly once, as the first frame.
	InitialState *InitialState `protobuf:"bytes,1,opt,name=initial_state,json=initialState,proto3,oneof"`
}

type HotkeyStreamFrame_Event struct {
	// a single semantic hotkey transition observed after the
	// initial snapshot was delivered.
	Event *HotkeyEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

func (*HotkeyStreamFrame_InitialState) isHotkeyStreamFrame_Payload() {}

func (*HotkeyStreamFrame_Event) isHotkeyStreamFrame_Payload() {}

// InitialState is the synchronous snapshot the daemon sends as the
// very first frame on every StreamHotkeyEvents subscription. It lets
// the UI converge to the daemon's view without a separate
// GetHotkeyState round trip — no race window between probe and
// subscribe.
type InitialState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// whether the daemon currently considers itself recording (the
	// user was holding the hotkey at the moment of subscribe, or a
	// TOGGLE press has not yet been balanced by another TOGGLE).
	State HotkeyState `protobuf:"varint,1,opt,name=state,proto3,enum=a2text.v1.HotkeyState" json:"state,omitempty"`
	// active hotkey mode the daemon read from its config. The UI uses
	// it to know how to interpret upcoming HotkeyEvent.kind values.
	Mode HotkeyMode `protobuf:"varint,2,opt,name=mode,proto3,enum=a2text.v1.HotkeyMode" json:"mode,omitempty"`
	// the inject_token of the cycle currently in flight, if state is
	// HOTKEY_STATE_RECORDING. Lets a UI that reconnected in the middle
	// of an active recording (after its own crash or restart) pick up
	// the live token and still legitimately complete the cycle with
	// Inject. Empty when state is HOTKEY_STATE_IDLE.
	ActiveInjectToken string `protobuf:"bytes,3,opt,name=active_inject_token,json=activeInjectToken,proto3" json:"active_inject_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InitialState) Reset() {
	*x = InitialState{}
	mi := &file_a2text_v1_keyboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialState) ProtoMessage() {}

func (x *InitialState) ProtoReflect() protoreflect.Message {
	mi := &file_a2text_v1_keyboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialState.ProtoReflect.Descriptor instead.
func (*InitialState) Descriptor() ([]byte, []int) {
	return file_a2text_v1_keyboard_proto_rawDescGZIP(), []int{2}
}

func (x *InitialState) GetState() HotkeyState {
	if x != nil {
		return x.State
	}
	return HotkeyState_HOTKEY_STATE_INVALID
}

func (x *InitialState) GetMode() HotkeyMode {
	if x != nil {
		return x.Mode
	}
	return HotkeyMode_HOTKEY_MODE_INVALID
}

func (x *InitialState) GetActiveInjectToken() string {
	if x != nil {
		return x.ActiveInjectToken
	}
	return ""
}

// HotkeyEvent represents a single semantic hotkey transition. The kind
// field is self-describing: PRESS/RELEASE imply HOLD mode, TOGGLE
// implies TOGGLE mode (see HotkeyEventKind).
type HotkeyEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind of the transition (press, release, or toggle).
	Kind HotkeyEventKind `protobuf:"varint,1,opt,name=kind,proto3,enum=a2text.v1.HotkeyEventKind" json:"kind,omitempty"`
	// wall-clock time the daemon read the event from the kernel.
	EmitTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=emit_time,json=emitTime,proto3" json:"emit_time,omitempty"`
	// monotonically increasing per-subscription counter, starting at 1
	// for the first event the daemon delivers on this stream. The
	// counter is reset every time a new StreamHotkeyEvents call is
	// accepted. Clients use it to detect drops under the lossy
	// ring-buffer policy: any gap (next_sequence != last_sequence + 1)
	// means the daemon discarded one or more frames it could not push
	// to a slow consumer.
	Sequence uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// daemon-issued token bound to the recording cycle this event
	// belongs to. Populated on every event that is part of a cycle —
	// PRESS and RELEASE in HOLD mode, both TOGGLE events in TOGGLE
	// mode — and all events of one cycle carry the same value. The
	// daemon mints the token on the cycle-start event (PRESS, first
	// TOGGLE) and reuses it verbatim on the cycle-end event (RELEASE,
	// second TOGGLE). UIs hand this token to KeyboardService.Inject
	// when the transcript is ready: the daemon rejects Inject calls
	// whose token it did not issue, is expired, or has already been
	// consumed, which simultaneously authorises the call and makes
	// retries idempotent. The token is wire-encoded as a string; the
	// daemon currently emits 16-byte random values (UUIDv4-shaped)
	// but clients must treat it as an opaque identifier.
	InjectToken   string `protobuf:"bytes,4,opt,name=inject_token,json=injectToken,proto3" json:"inject_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotkeyEvent) Reset() {
	*x = HotkeyEvent{}
	mi := &file_a2text_v1_keyboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotkeyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotkeyEvent) ProtoMessage() {}

func (x *HotkeyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_a2text_v1_keyboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotkeyEvent.ProtoReflect.Descriptor instead.
func (*HotkeyEvent) Descriptor() ([]byte, []int) {
	return file_a2text_v1_keyboard_proto_rawDescGZIP(), []int{3}
}

func (x *HotkeyEvent) GetKind() HotkeyEventKind {
	if x != nil {
		return x.Kind
	}
	return HotkeyEventKind_HOTKEY_EVENT_KIND_INVALID
}

func (x *HotkeyEvent) GetEmitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EmitTime
	}
	return nil
}

func (x *HotkeyEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *HotkeyEvent) GetInjectToken() string {
	if x != nil {
		return x.InjectToken
	}
	return ""
}

// InjectRequest carries the transcript the UI wants written into the
// user's focused window. The daemon picks the strategy.
type InjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the UTF-8 transcript to deliver. The daemon may type it directly
	// (uinput type mode) or treat it as the expected clipboard payload
	// when it presses Ctrl+V (uinput paste mode).
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// daemon-issued token bound to the recording cycle that produced
	// this transcript. Required: the daemon rejects requests with an
	// empty, unknown, expired, or already-consumed token. This
	// double-duties as authorisation (only hotkey-driven or
	// StartCycle-initiated cycles can drive Inject) and as the
	// idempotency key (a retry with the same token returns the cached
	// response without performing a second uinput action). Sourced
	// from HotkeyEvent.inject_token, StartCycleResponse.inject_token,
	// or InitialState.active_inject_token.
	InjectToken   string `protobuf:"bytes,2,opt,name=inject_token,json=injectToken,proto3" json:"inject_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectRequest) Reset() {
	*x = InjectRequest{}
	mi := &file_a2text_v1_keyboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectRequest) ProtoMessage() {}

func (x *InjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2text_v1_keyboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectRequest.ProtoReflect.Descriptor instead.
func (*InjectRequest) Descriptor() ([]byte, []int) {
	return file_a2text_v1_keyboard_proto_rawDescGZIP(), []int{4}
}

func (x *InjectRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *InjectRequest) GetInjectToken() string {
	if x != nil {
		return x.InjectToken
	}
	return ""
}

// InjectResponse reports what the daemon actually did, so the UI can
// distinguish "nothing typed" from "fully typed" and surface the
// active strategy without parsing daemon logs.
type InjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// strategy the daemon executed for this request.
	Mode InjectMode `protobuf:"varint,1,opt,name=mode,proto3,enum=a2text.v1.InjectMode" json:"mode,omitempty"`
	// number of low-level key events the daemon wrote to /dev/uinput.
	// Zero means the request was a no-op (e.g. type mode with only
	// unmappable codepoints).
	EventsWritten int32 `protobuf:"varint,2,opt,name=events_written,json=eventsWritten,proto3" json:"events_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectResponse) Reset() {
	*x = InjectResponse{}
	mi := &file_a2text_v1_keyboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectResponse) ProtoMessage() {}

func (x *InjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_a2text_v1_keyboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectResponse.ProtoReflect.Descriptor instead.
func (*InjectResponse) Descriptor() ([]byte, []int) {
	return file_a2text_v1_keyboard_proto_rawDescGZIP(), []int{5}
}

func (x *InjectResponse) GetMode() InjectMode {
	if x != nil {
		return x.Mode
	}
	return InjectMode_INJECT_MODE_INVALID
}

func (x *InjectResponse) GetEventsWritten() int32 {
	if x != nil {
		return x.EventsWritten
	}
	return 0
}

// StartCycleRequest is empty by design. Future fields (a caller hint
// for the cycle's output policy, an explicit timeout override) will
// be added with new tag numbers when there is a real reason.
type StartCycleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCycleRequest) Reset() {
	*x = StartCycleRequest{}
	mi := &file_a2text_v1_keyboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCycleRequest) ProtoMessage() {}

func (x *StartCycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2text_v1_keyboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCycleRequest.ProtoReflect.Descriptor instead.
func (*StartCycleRequest) Descriptor() ([]byte, []int) {
	return file_a2text_v1_keyboard_proto_rawDescGZIP(), []int{6}
}

// StartCycleResponse carries the inject_token the caller must hand
// back to Inject when the cycle's transcript is ready.
type StartCycleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// opaque token bound to this cycle. Identical to the value the
	// daemon also embeds in the corresponding HotkeyEvent on the
	// StreamHotkeyEvents stream, so a UI that drives StartCycle and a
	// UI that listens on the stream see the same identifier.
	InjectToken string `protobuf:"bytes,1,opt,name=inject_token,json=injectToken,proto3" json:"inject_token,omitempty"`
	// wall-clock time after which the daemon will refuse Inject calls
	// carrying this token. Clients use it to surface a "transcript
	// expired" warning if their pipeline takes too long.
	ExpireTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCycleResponse) Reset() {
	*x = StartCycleResponse{}
	mi := &file_a2text_v1_keyboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCycleResponse) ProtoMessage() {}

func (x *StartCycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_a2text_v1_keyboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCycleResponse.ProtoReflect.Descriptor instead.
func (*StartCycleResponse) Descriptor() ([]byte, []int) {
	return file_a2text_v1_keyboard_proto_rawDescGZIP(), []int{7}
}

func (x *StartCycleResponse) GetInjectToken() string {
	if x != nil {
		return x.InjectToken
	}
	return ""
}

func (x *StartCycleResponse) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

var File_a2text_v1_keyboard_proto protoreflect.FileDescriptor

const file_a2text_v1_keyboard_proto_rawDesc = "" +
	"\n" +
	"\x18a2text/v1/keyboard.proto\x12\ta2text.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1b\n" +
	"\x19StreamHotkeyEventsRequest\"\x8e\x01\n" +
	"\x11HotkeyStreamFrame\x12>\n" +
	"\rinitial_state\x18\x01 \x01(\v2\x17.a2text.v1.InitialStateH\x00R\finitialState\x12.\n" +
	"\x05event\x18\x02 \x01(\v2\x16.a2text.v1.HotkeyEventH\x00R\x05eventB\t\n" +
	"\apayload\"\x97\x01\n" +
	"\fInitialState\x12,\n" +
	"\x05state\x18\x01 \x01(\x0e2\x16.a2text.v1.HotkeyStateR\x05state\x12)\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x15.a2text.v1.HotkeyModeR\x04mode\x12.\n" +
	"\x13active_inject_token\x18\x03 \x01(\tR\x11activeInjectToken\"\xb5\x01\n" +
	"\vHotkeyEvent\x12.\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1a.a2text.v1.HotkeyEventKindR\x04kind\x127\n" +
	"\temit_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bemitTime\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12!\n" +
	"\finject_token\x18\x04 \x01(\tR\vinjectToken\"F\n" +
	"\rInjectRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12!\n" +
	"\finject_token\x18\x02 \x01(\tR\vinjectToken\"b\n" +
	"\x0eInjectResponse\x12)\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x15.a2text.v1.InjectModeR\x04mode\x12%\n" +
	"\x0eevents_written\x18\x02 \x01(\x05R\reventsWritten\"\x13\n" +
	"\x11StartCycleRequest\"t\n" +
	"\x12StartCycleResponse\x12!\n" +
	"\finject_token\x18\x01 \x01(\tR\vinjectToken\x12;\n" +
	"\vexpire_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireTime*Z\n" +
	"\vHotkeyState\x12\x18\n" +
	"\x14HOTKEY_STATE_INVALID\x10\x00\x12\x15\n" +
	"\x11HOTKEY_STATE_IDLE\x10\x01\x12\x1a\n" +
	"\x16HOTKEY_STATE_RECORDING\x10\x02*S\n" +
	"\n" +
	"HotkeyMode\x12\x17\n" +
	"\x13HOTKEY_MODE_INVALID\x10\x00\x12\x14\n" +
	"\x10HOTKEY_MODE_HOLD\x10\x01\x12\x16\n" +
	"\x12HOTKEY_MODE_TOGGLE\x10\x02*\x8a\x01\n" +
	"\x0fHotkeyEventKind\x12\x1d\n" +
	"\x19HOTKEY_EVENT_KIND_INVALID\x10\x00\x12\x1b\n" +
	"\x17HOTKEY_EVENT_KIND_PRESS\x10\x01\x12\x1d\n" +
	"\x19HOTKEY_EVENT_KIND_RELEASE\x10\x02\x12\x1c\n" +
	"\x18HOTKEY_EVENT_KIND_TOGGLE\x10\x03*m\n" +
	"\n" +
	"InjectMode\x12\x17\n" +
	"\x13INJECT_MODE_INVALID\x10\x00\x12\x19\n" +
	"\x15INJECT_MODE_CLIPBOARD\x10\x01\x12\x15\n" +
	"\x11INJECT_MODE_PASTE\x10\x02\x12\x14\n" +
	"\x10INJECT_MODE_TYPE\x10\x032\xf7\x01\n" +
	"\x0fKeyboardService\x12Z\n" +
	"\x12StreamHotkeyEvents\x12$.a2text.v1.StreamHotkeyEventsRequest\x1a\x1c.a2text.v1.HotkeyStreamFrame0\x01\x12=\n" +
	"\x06Inject\x12\x18.a2text.v1.InjectRequest\x1a\x19.a2text.v1.InjectResponse\x12I\n" +
	"\n" +
	"StartCycle\x12\x1c.a2text.v1.StartCycleRequest\x1a\x1d.a2text.v1.StartCycleResponseB;Z9github.com/partyzanex/a2text/pkg/proto/a2text/v1;a2textv1b\x06proto3"

var (
	file_a2text_v1_keyboard_proto_rawDescOnce sync.Once
	file_a2text_v1_keyboard_proto_rawDescData []byte
)

func file_a2text_v1_keyboard_proto_rawDescGZIP() []byte {
	file_a2text_v1_keyboard_proto_rawDescOnce.Do(func() {
		file_a2text_v1_keyboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_a2text_v1_keyboard_proto_rawDesc), len(file_a2text_v1_keyboard_proto_rawDesc)))
	})
	return file_a2text_v1_keyboard_proto_rawDescData
}

var file_a2text_v1_keyboard_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_a2text_v1_keyboard_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_a2text_v1_keyboard_proto_goTypes = []any{
	(HotkeyState)(0),                  // 0: a2text.v1.HotkeyState
	(HotkeyMode)(0),                   // 1: a2text.v1.HotkeyMode
	(HotkeyEventKind)(0),              // 2: a2text.v1.HotkeyEventKind
	(InjectMode)(0),                   // 3: a2text.v1.InjectMode
	(*StreamHotkeyEventsRequest)(nil), // 4: a2text.v1.StreamHotkeyEventsRequest
	(*HotkeyStreamFrame)(nil),         // 5: a2text.v1.HotkeyStreamFrame
	(*InitialState)(nil),              // 6: a2text.v1.InitialState
	(*HotkeyEvent)(nil),               // 7: a2text.v1.HotkeyEvent
	(*InjectRequest)(nil),             // 8: a2text.v1.InjectRequest
	(*InjectResponse)(nil),            // 9: a2text.v1.InjectResponse
	(*StartCycleRequest)(nil),         // 10: a2text.v1.StartCycleRequest
	(*StartCycleResponse)(nil),        // 11: a2text.v1.StartCycleResponse
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
}
var file_a2text_v1_keyboard_proto_depIdxs = []int32{
	6,  // 0: a2text.v1.HotkeyStreamFrame.initial_state:type_name -> a2text.v1.InitialState
	7,  // 1: a2text.v1.HotkeyStreamFrame.event:type_name -> a2text.v1.HotkeyEvent
	0,  // 2: a2text.v1.InitialState.state:type_name -> a2text.v1.HotkeyState
	1,  // 3: a2text.v1.InitialState.mode:type_name -> a2text.v1.HotkeyMode
	2,  // 4: a2text.v1.HotkeyEvent.kind:type_name -> a2text.v1.HotkeyEventKind
	12, // 5: a2text.v1.HotkeyEvent.emit_time:type_name -> google.protobuf.Timestamp
	3,  // 6: a2text.v1.InjectResponse.mode:type_name -> a2text.v1.InjectMode
	12, // 7: a2text.v1.StartCycleResponse.expire_time:type_name -> google.protobuf.Timestamp
	4,  // 8: a2text.v1.KeyboardService.StreamHotkeyEvents:input_type -> a2text.v1.StreamHotkeyEventsRequest
	8,  // 9: a2text.v1.KeyboardService.Inject:input_type -> a2text.v1.InjectRequest
	10, // 10: a2text.v1.KeyboardService.StartCycle:input_type -> a2text.v1.StartCycleRequest
	5,  // 11: a2text.v1.KeyboardService.StreamHotkeyEvents:output_type -> a2text.v1.HotkeyStreamFrame
	9,  // 12: a2text.v1.KeyboardService.Inject:output_type -> a2text.v1.InjectResponse
	11, // 13: a2text.v1.KeyboardService.StartCycle:output_type -> a2text.v1.StartCycleResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_a2text_v1_keyboard_proto_init() }
func file_a2text_v1_keyboard_proto_init() {
	if File_a2text_v1_keyboard_proto != nil {
		return
	}
	file_a2text_v1_keyboard_proto_msgTypes[1].OneofWrappers = []any{
		(*HotkeyStreamFrame_InitialState)(nil),
		(*HotkeyStreamFrame_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_a2text_v1_keyboard_proto_rawDesc), len(file_a2text_v1_keyboard_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_a2text_v1_keyboard_proto_goTypes,
		DependencyIndexes: file_a2text_v1_keyboard_proto_depIdxs,
		EnumInfos:         file_a2text_v1_keyboard_proto_enumTypes,
		MessageInfos:      file_a2text_v1_keyboard_proto_msgTypes,
	}.Build()
	File_a2text_v1_keyboard_proto = out.File
	file_a2text_v1_keyboard_proto_goTypes = nil
	file_a2text_v1_keyboard_proto_depIdxs = nil
}
