// Secret subsystem of a2textd.
//
// The daemon owns a key-value store on disk (under /var/lib/a2textd/)
// and exposes it through this service. The store holds provider API
// keys and any other long-lived secrets the daemon itself needs at
// runtime.
//
// Storage protection is by access control, not by application-level
// encryption. The on-disk file is owned by a dedicated system user
// (a2textd:a2textd) with mode 0600; combined with systemd hardening
// directives on the unit (NoNewPrivileges, ProtectSystem, ProtectHome,
// PrivateTmp, dropped capabilities) this keeps the file unreadable to
// every non-root process on the machine. Disk-level encryption (LUKS)
// is the recommended OS-level mitigation against cold-disk theft and
// is assumed to be present on hostile-loss threat models. Application-
// level encryption-at-rest may be enabled per config later if a real
// requirement appears (compliance, untrusted-backup scenarios) — when
// it does the on-disk format changes but the wire contract here does
// not.
//
// Asymmetric API by design:
//   * Writes (Set) and metadata reads (List) are exposed.
//   * Plaintext reads are NOT — there is no Get RPC. The daemon reads
//     the value internally when an STT provider needs it; the UI must
//     keep its own copy if it wants to display the value back to the
//     user.
//   * Delete and rotate will be added with new RPCs when there is a
//     real reason.
//
// This minimises the IPC attack surface: a same-UID adversary that
// somehow obtains a valid mTLS client cert still cannot read stored
// keys back, only overwrite them.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: a2text/v1/secret.proto

package a2textv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SetSecretRequest carries one key/value pair.
type SetSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// logical key the value is bound to. Conventionally the provider
	// name ("openai", "deepgram") but free-form strings are accepted.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// raw secret value. Bytes (not string) on the wire because real
	// secrets are not always valid UTF-8: PEM private keys, raw byte
	// tokens, OAuth refresh tokens with control characters all need
	// to round-trip safely. The daemon never echoes this back in any
	// subsequent RPC.
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecretRequest) Reset() {
	*x = SetSecretRequest{}
	mi := &file_a2text_v1_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretRequest) ProtoMessage() {}

func (x *SetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2text_v1_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecretRequest.ProtoReflect.Descriptor instead.
func (*SetSecretRequest) Descriptor() ([]byte, []int) {
	return file_a2text_v1_secret_proto_rawDescGZIP(), []int{0}
}

func (x *SetSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetSecretRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// SetSecretResponse acknowledges the write happened.
type SetSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server-side timestamp when the entry was written.
	StoreTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=store_time,json=storeTime,proto3" json:"store_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecretResponse) Reset() {
	*x = SetSecretResponse{}
	mi := &file_a2text_v1_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretResponse) ProtoMessage() {}

func (x *SetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_a2text_v1_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecretResponse.ProtoReflect.Descriptor instead.
func (*SetSecretResponse) Descriptor() ([]byte, []int) {
	return file_a2text_v1_secret_proto_rawDescGZIP(), []int{1}
}

func (x *SetSecretResponse) GetStoreTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StoreTime
	}
	return nil
}

// ListSecretsRequest is empty by design. Filter fields may be added
// later (prefix match, only-set-after, etc).
type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_a2text_v1_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2text_v1_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_a2text_v1_secret_proto_rawDescGZIP(), []int{2}
}

// ListSecretsResponse describes every key currently in the store.
type ListSecretsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// one entry per key. Order is not guaranteed.
	Secrets       []*SecretMeta `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_a2text_v1_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_a2text_v1_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_a2text_v1_secret_proto_rawDescGZIP(), []int{3}
}

func (x *ListSecretsResponse) GetSecrets() []*SecretMeta {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// SecretMeta describes one stored key without revealing its value.
type SecretMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the logical key.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// server-side timestamp when the current value was written.
	StoreTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=store_time,json=storeTime,proto3" json:"store_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretMeta) Reset() {
	*x = SecretMeta{}
	mi := &file_a2text_v1_secret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretMeta) ProtoMessage() {}

func (x *SecretMeta) ProtoReflect() protoreflect.Message {
	mi := &file_a2text_v1_secret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretMeta.ProtoReflect.Descriptor instead.
func (*SecretMeta) Descriptor() ([]byte, []int) {
	return file_a2text_v1_secret_proto_rawDescGZIP(), []int{4}
}

func (x *SecretMeta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SecretMeta) GetStoreTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StoreTime
	}
	return nil
}

var File_a2text_v1_secret_proto protoreflect.FileDescriptor

const file_a2text_v1_secret_proto_rawDesc = "" +
	"\n" +
	"\x16a2text/v1/secret.proto\x12\ta2text.v1\x1a\x1fgoogle/protobuf/timestamp.proto\":\n" +
	"\x10SetSecretRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"N\n" +
	"\x11SetSecretResponse\x129\n" +
	"\n" +
	"store_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstoreTime\"\x14\n" +
	"\x12ListSecretsRequest\"F\n" +
	"\x13ListSecretsResponse\x12/\n" +
	"\asecrets\x18\x01 \x03(\v2\x15.a2text.v1.SecretMetaR\asecrets\"Y\n" +
	"\n" +
	"SecretMeta\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\n" +
	"store_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstoreTime2\x98\x01\n" +
	"\rSecretService\x12@\n" +
	"\x03Set\x12\x1b.a2text.v1.SetSecretRequest\x1a\x1c.a2text.v1.SetSecretResponse\x12E\n" +
	"\x04List\x12\x1d.a2text.v1.ListSecretsRequest\x1a\x1e.a2text.v1.ListSecretsResponseB;Z9github.com/partyzanex/a2text/pkg/proto/a2text/v1;a2textv1b\x06proto3"

var (
	file_a2text_v1_secret_proto_rawDescOnce sync.Once
	file_a2text_v1_secret_proto_rawDescData []byte
)

func file_a2text_v1_secret_proto_rawDescGZIP() []byte {
	file_a2text_v1_secret_proto_rawDescOnce.Do(func() {
		file_a2text_v1_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_a2text_v1_secret_proto_rawDesc), len(file_a2text_v1_secret_proto_rawDesc)))
	})
	return file_a2text_v1_secret_proto_rawDescData
}

var file_a2text_v1_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_a2text_v1_secret_proto_goTypes = []any{
	(*SetSecretRequest)(nil),      // 0: a2text.v1.SetSecretRequest
	(*SetSecretResponse)(nil),     // 1: a2text.v1.SetSecretResponse
	(*ListSecretsRequest)(nil),    // 2: a2text.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),   // 3: a2text.v1.ListSecretsResponse
	(*SecretMeta)(nil),            // 4: a2text.v1.SecretMeta
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_a2text_v1_secret_proto_depIdxs = []int32{
	5, // 0: a2text.v1.SetSecretResponse.store_time:type_name -> google.protobuf.Timestamp
	4, // 1: a2text.v1.ListSecretsResponse.secrets:type_name -> a2text.v1.SecretMeta
	5, // 2: a2text.v1.SecretMeta.store_time:type_name -> google.protobuf.Timestamp
	0, // 3: a2text.v1.SecretService.Set:input_type -> a2text.v1.SetSecretRequest
	2, // 4: a2text.v1.SecretService.List:input_type -> a2text.v1.ListSecretsRequest
	1, // 5: a2text.v1.SecretService.Set:output_type -> a2text.v1.SetSecretResponse
	3, // 6: a2text.v1.SecretService.List:output_type -> a2text.v1.ListSecretsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_a2text_v1_secret_proto_init() }
func file_a2text_v1_secret_proto_init() {
	if File_a2text_v1_secret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_a2text_v1_secret_proto_rawDesc), len(file_a2text_v1_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_a2text_v1_secret_proto_goTypes,
		DependencyIndexes: file_a2text_v1_secret_proto_depIdxs,
		MessageInfos:      file_a2text_v1_secret_proto_msgTypes,
	}.Build()
	File_a2text_v1_secret_proto = out.File
	file_a2text_v1_secret_proto_goTypes = nil
	file_a2text_v1_secret_proto_depIdxs = nil
}
