// Secret subsystem of a2textd.
//
// The daemon owns a key-value store on disk (under /var/lib/a2textd/)
// and exposes it through this service. The store holds provider API
// keys and any other long-lived secrets the daemon itself needs at
// runtime.
//
// Storage protection is by access control, not by application-level
// encryption. The on-disk file is owned by a dedicated system user
// (a2textd:a2textd) with mode 0600; combined with systemd hardening
// directives on the unit (NoNewPrivileges, ProtectSystem, ProtectHome,
// PrivateTmp, dropped capabilities) this keeps the file unreadable to
// every non-root process on the machine. Disk-level encryption (LUKS)
// is the recommended OS-level mitigation against cold-disk theft and
// is assumed to be present on hostile-loss threat models. Application-
// level encryption-at-rest may be enabled per config later if a real
// requirement appears (compliance, untrusted-backup scenarios) — when
// it does the on-disk format changes but the wire contract here does
// not.
//
// Asymmetric API by design:
//   * Writes (Set) and metadata reads (List) are exposed.
//   * Plaintext reads are NOT — there is no Get RPC. The daemon reads
//     the value internally when an STT provider needs it; the UI must
//     keep its own copy if it wants to display the value back to the
//     user.
//   * Delete and rotate will be added with new RPCs when there is a
//     real reason.
//
// This minimises the IPC attack surface: a same-UID adversary that
// somehow obtains a valid mTLS client cert still cannot read stored
// keys back, only overwrite them.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.1
// source: a2text/v1/secret.proto

package a2textv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretService_Set_FullMethodName  = "/a2text.v1.SecretService/Set"
	SecretService_List_FullMethodName = "/a2text.v1.SecretService/List"
)

// SecretServiceClient is the client API for SecretService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SecretService is the wire interface for the daemon-owned secret
// store. Every RPC is invoked under mTLS on the loopback gRPC
// channel.
type SecretServiceClient interface {
	// Set writes (or overwrites) the value bound to the given key. The
	// daemon persists the entry to its access-controlled storage and
	// returns the server-side store timestamp so the UI can show
	// "last updated".
	Set(ctx context.Context, in *SetSecretRequest, opts ...grpc.CallOption) (*SetSecretResponse, error)
	// List returns metadata for every key currently present in the
	// store. Values are never returned — callers receive key names and
	// bookkeeping fields only.
	List(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error)
}

type secretServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretServiceClient(cc grpc.ClientConnInterface) SecretServiceClient {
	return &secretServiceClient{cc}
}

func (c *secretServiceClient) Set(ctx context.Context, in *SetSecretRequest, opts ...grpc.CallOption) (*SetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSecretResponse)
	err := c.cc.Invoke(ctx, SecretService_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) List(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretsResponse)
	err := c.cc.Invoke(ctx, SecretService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretServiceServer is the server API for SecretService service.
// All implementations must embed UnimplementedSecretServiceServer
// for forward compatibility.
//
// SecretService is the wire interface for the daemon-owned secret
// store. Every RPC is invoked under mTLS on the loopback gRPC
// channel.
type SecretServiceServer interface {
	// Set writes (or overwrites) the value bound to the given key. The
	// daemon persists the entry to its access-controlled storage and
	// returns the server-side store timestamp so the UI can show
	// "last updated".
	Set(context.Context, *SetSecretRequest) (*SetSecretResponse, error)
	// List returns metadata for every key currently present in the
	// store. Values are never returned — callers receive key names and
	// bookkeeping fields only.
	List(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error)
	mustEmbedUnimplementedSecretServiceServer()
}

// UnimplementedSecretServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretServiceServer struct{}

func (UnimplementedSecretServiceServer) Set(context.Context, *SetSecretRequest) (*SetSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedSecretServiceServer) List(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSecretServiceServer) mustEmbedUnimplementedSecretServiceServer() {}
func (UnimplementedSecretServiceServer) testEmbeddedByValue()                       {}

// UnsafeSecretServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretServiceServer will
// result in compilation errors.
type UnsafeSecretServiceServer interface {
	mustEmbedUnimplementedSecretServiceServer()
}

func RegisterSecretServiceServer(s grpc.ServiceRegistrar, srv SecretServiceServer) {
	// If the following call panics, it indicates UnimplementedSecretServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretService_ServiceDesc, srv)
}

func _SecretService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).Set(ctx, req.(*SetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).List(ctx, req.(*ListSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretService_ServiceDesc is the grpc.ServiceDesc for SecretService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "a2text.v1.SecretService",
	HandlerType: (*SecretServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _SecretService_Set_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SecretService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "a2text/v1/secret.proto",
}
