// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mocks_test.go -package=transcribe_test
//

// Package transcribe_test is a generated GoMock package.
package transcribe_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConverter is a mock of Converter interface.
type MockConverter struct {
	ctrl     *gomock.Controller
	recorder *MockConverterMockRecorder
	isgomock struct{}
}

// MockConverterMockRecorder is the mock recorder for MockConverter.
type MockConverterMockRecorder struct {
	mock *MockConverter
}

// NewMockConverter creates a new mock instance.
func NewMockConverter(ctrl *gomock.Controller) *MockConverter {
	mock := &MockConverter{ctrl: ctrl}
	mock.recorder = &MockConverterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConverter) EXPECT() *MockConverterMockRecorder {
	return m.recorder
}

// ToWAV mocks base method.
func (m *MockConverter) ToWAV(ctx context.Context, inputPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToWAV", ctx, inputPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToWAV indicates an expected call of ToWAV.
func (mr *MockConverterMockRecorder) ToWAV(ctx, inputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToWAV", reflect.TypeOf((*MockConverter)(nil).ToWAV), ctx, inputPath)
}

// MockTranscriber is a mock of Transcriber interface.
type MockTranscriber struct {
	ctrl     *gomock.Controller
	recorder *MockTranscriberMockRecorder
	isgomock struct{}
}

// MockTranscriberMockRecorder is the mock recorder for MockTranscriber.
type MockTranscriberMockRecorder struct {
	mock *MockTranscriber
}

// NewMockTranscriber creates a new mock instance.
func NewMockTranscriber(ctrl *gomock.Controller) *MockTranscriber {
	mock := &MockTranscriber{ctrl: ctrl}
	mock.recorder = &MockTranscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranscriber) EXPECT() *MockTranscriberMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockTranscriber) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTranscriberMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTranscriber)(nil).Close))
}

// DetectLanguage mocks base method.
func (m *MockTranscriber) DetectLanguage(ctx context.Context, wavPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetectLanguage", ctx, wavPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetectLanguage indicates an expected call of DetectLanguage.
func (mr *MockTranscriberMockRecorder) DetectLanguage(ctx, wavPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectLanguage", reflect.TypeOf((*MockTranscriber)(nil).DetectLanguage), ctx, wavPath)
}

// LoadModel mocks base method.
func (m *MockTranscriber) LoadModel(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadModel", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadModel indicates an expected call of LoadModel.
func (mr *MockTranscriberMockRecorder) LoadModel(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadModel", reflect.TypeOf((*MockTranscriber)(nil).LoadModel), path)
}

// ReloadModel mocks base method.
func (m *MockTranscriber) ReloadModel(newPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReloadModel", newPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReloadModel indicates an expected call of ReloadModel.
func (mr *MockTranscriberMockRecorder) ReloadModel(newPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadModel", reflect.TypeOf((*MockTranscriber)(nil).ReloadModel), newPath)
}

// Transcribe mocks base method.
func (m *MockTranscriber) Transcribe(ctx context.Context, wavPath, lang string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transcribe", ctx, wavPath, lang)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transcribe indicates an expected call of Transcribe.
func (mr *MockTranscriberMockRecorder) Transcribe(ctx, wavPath, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transcribe", reflect.TypeOf((*MockTranscriber)(nil).Transcribe), ctx, wavPath, lang)
}
