// Code generated by MockGen. DO NOT EDIT.
// Source: sdnotify.go
//
// Generated by this command:
//
//	mockgen -package=cmd -destination=sdnotify_mocks_test.go -source=sdnotify.go NotifySender
//

// Package cmd is a generated GoMock package.
package sysd

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotifySender is a mock of NotifySender interface.
type MockNotifySender struct {
	ctrl     *gomock.Controller
	recorder *MockNotifySenderMockRecorder
	isgomock struct{}
}

// MockNotifySenderMockRecorder is the mock recorder for MockNotifySender.
type MockNotifySenderMockRecorder struct {
	mock *MockNotifySender
}

// NewMockNotifySender creates a new mock instance.
func NewMockNotifySender(ctrl *gomock.Controller) *MockNotifySender {
	mock := &MockNotifySender{ctrl: ctrl}
	mock.recorder = &MockNotifySenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifySender) EXPECT() *MockNotifySenderMockRecorder {
	return m.recorder
}

// Active mocks base method.
func (m *MockNotifySender) Active() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Active")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Active indicates an expected call of Active.
func (mr *MockNotifySenderMockRecorder) Active() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Active", reflect.TypeOf((*MockNotifySender)(nil).Active))
}

// Notify mocks base method.
func (m *MockNotifySender) Notify(state string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", state)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Notify indicates an expected call of Notify.
func (mr *MockNotifySenderMockRecorder) Notify(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockNotifySender)(nil).Notify), state)
}
