package stt

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"time"

	"github.com/partyzanex/a2text/pkg/sttx"
)

const (
	defaultMaxFileSize = 20 << 20 // 20 MB fallback if not set via config
	deepgramAPITimeout = 60 * time.Second
)

// DeepgramTranscriber implements CloudTranscriber using Deepgram API.
type DeepgramTranscriber struct {
	client      *http.Client
	log         *slog.Logger
	apiKey      string
	apiURL      string
	maxFileSize int64
}

// NewDeepgramTranscriber creates a new DeepgramTranscriber.
// If log is nil, slog.Default() is used.
// If apiURL is empty, it defaults to https://api.deepgram.com/v1/listen.
// If maxFileSize <= 0, a 20 MB default is used.
// validateWavPath ensures the given WAV file path is safe to open.
// Checks that the path is not a symlink, is a regular file.
// Primarily used for paths generated by internal recording (os.CreateTemp).
func validateWavPath(wavPath string) error {
	if wavPath == "" {
		return fmt.Errorf("%w: empty wav path", sttx.ErrTranscribeFailed)
	}

	// Ensure path is absolute to prevent path traversal attacks.
	if !filepath.IsAbs(wavPath) {
		return fmt.Errorf("%w: wav path must be absolute", sttx.ErrTranscribeFailed)
	}

	// Use Lstat to detect symlinks without following them.
	fileInfo, err := os.Lstat(wavPath)
	if err != nil {
		return fmt.Errorf("%w: stat wav file: %w", sttx.ErrTranscribeFailed, err)
	}

	// Reject symlinks to prevent symlink-based file inclusion attacks.
	if fileInfo.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("%w: wav path is a symlink", sttx.ErrTranscribeFailed)
	}

	// Ensure it's a regular file, not a directory or device.
	if !fileInfo.Mode().IsRegular() {
		return fmt.Errorf("%w: wav path is not a regular file", sttx.ErrTranscribeFailed)
	}

	// Ensure file has reasonable size (not empty).
	if fileInfo.Size() <= 0 {
		return fmt.Errorf("%w: wav file is empty", sttx.ErrTranscribeFailed)
	}

	// Ensure file has .wav extension.
	if filepath.Ext(wavPath) != ".wav" {
		return fmt.Errorf("%w: wav path must have .wav extension", sttx.ErrTranscribeFailed)
	}

	return nil
}

func NewDeepgramTranscriber(apiKey, apiURL string, maxFileSize int64, log *slog.Logger) *DeepgramTranscriber {
	if log == nil {
		log = slog.Default()
	}

	if apiURL == "" {
		apiURL = "https://api.deepgram.com/v1/listen"
	}

	if maxFileSize <= 0 {
		maxFileSize = defaultMaxFileSize
	}

	return &DeepgramTranscriber{
		apiKey:      apiKey,
		apiURL:      apiURL,
		maxFileSize: maxFileSize,
		client:      &http.Client{Timeout: deepgramAPITimeout},
		log:         log,
	}
}

// Name returns the transcriber name.
func (d *DeepgramTranscriber) Name() string {
	return "deepgram"
}

// buildDeepgramURL appends Deepgram-specific query parameters to apiURL.
func buildDeepgramURL(apiURL, lang string) (string, error) {
	parsedURL, err := url.Parse(apiURL)
	if err != nil {
		return "", fmt.Errorf("deepgram: %w", err)
	}

	query := parsedURL.Query()
	query.Set("model", "nova-2")

	if lang != "" && lang != langAuto {
		query.Set("language", lang)
	}

	parsedURL.RawQuery = query.Encode()

	return parsedURL.String(), nil
}

// parseDeepgramResponse extracts the transcript from a Deepgram JSON response body.
func parseDeepgramResponse(body []byte) (string, error) {
	var result struct {
		Results struct {
			Channels []struct {
				Alternatives []struct {
					Transcript string `json:"transcript"`
				} `json:"alternatives"`
			} `json:"channels"`
		} `json:"results"`
	}
	if err := json.Unmarshal(body, &result); err != nil {
		return "", fmt.Errorf("%w: failed to parse response: %w", sttx.ErrTranscribeFailed, err)
	}

	if len(result.Results.Channels) == 0 || len(result.Results.Channels[0].Alternatives) == 0 {
		return "", fmt.Errorf("%w: no transcription results in response", sttx.ErrTranscribeFailed)
	}

	return result.Results.Channels[0].Alternatives[0].Transcript, nil
}

// Transcribe sends the audio file to Deepgram API for transcription.
func (d *DeepgramTranscriber) Transcribe(ctx context.Context, wavPath, lang string) (string, error) {
	if err := validateWavPath(wavPath); err != nil {
		return "", err
	}

	file, err := os.Open(filepath.Clean(wavPath))
	if err != nil {
		return "", fmt.Errorf("%w: failed to open audio file: %w", sttx.ErrTranscribeFailed, err)
	}

	defer func() {
		if closeErr := file.Close(); closeErr != nil {
			d.log.Debug("failed to close audio file", slog.String("path", wavPath))
		}
	}()

	err = d.validateFileSize(file)
	if err != nil {
		return "", err
	}

	req, err := d.buildRequest(ctx, lang, file)
	if err != nil {
		return "", err
	}

	return d.executeRequest(req, wavPath, lang)
}

// DetectLanguage returns "auto" since Deepgram API auto-detects language.
func (d *DeepgramTranscriber) DetectLanguage(_ context.Context, _ string) (string, error) {
	return "auto", nil
}

// LoadModel is a no-op — no local model needed for the cloud transcriber.
func (d *DeepgramTranscriber) LoadModel(_ string) error { return nil }

// ReloadModel is a no-op — cloud transcriber doesn't support model reload.
func (d *DeepgramTranscriber) ReloadModel(_ string) error { return nil }

// Close is a no-op — no resources to release.
func (d *DeepgramTranscriber) Close() error { return nil }

// validateFileSize checks that the audio file does not exceed the configured limit.
func (d *DeepgramTranscriber) validateFileSize(file *os.File) error {
	info, err := file.Stat()
	if err != nil {
		return fmt.Errorf("%w: stat audio file: %w", sttx.ErrTranscribeFailed, err)
	}

	if info.Size() > d.maxFileSize {
		return fmt.Errorf(
			"%w: audio file %d bytes exceeds limit %d",
			sttx.ErrTranscribeFailed, info.Size(), d.maxFileSize,
		)
	}

	return nil
}

// buildRequest creates an HTTP request for the Deepgram API.
func (d *DeepgramTranscriber) buildRequest(ctx context.Context, lang string, body io.Reader) (*http.Request, error) {
	reqURL, err := buildDeepgramURL(d.apiURL, lang)
	if err != nil {
		return nil, fmt.Errorf("%w: failed to parse API URL: %w", sttx.ErrTranscribeFailed, err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, reqURL, body)
	if err != nil {
		return nil, fmt.Errorf("%w: failed to create request: %w", sttx.ErrTranscribeFailed, err)
	}

	req.Header.Set("Authorization", "Token "+d.apiKey)
	req.Header.Set("Content-Type", "audio/wav")

	return req, nil
}

// executeRequest sends the request and parses the transcription response.
func (d *DeepgramTranscriber) executeRequest(req *http.Request, wavPath, lang string) (string, error) {
	d.log.Info("sending request to Deepgram API", slog.String("wav", wavPath), slog.String("lang", lang))

	resp, err := d.client.Do(req)
	if err != nil {
		return "", fmt.Errorf("%w: request failed: %w", sttx.ErrTranscribeFailed, err)
	}
	defer func() {
		if closeErr := resp.Body.Close(); closeErr != nil {
			d.log.Debug("failed to close response body")
		}
	}()

	respBody, err := io.ReadAll(io.LimitReader(resp.Body, maxRespBodySize))
	if err != nil {
		return "", fmt.Errorf("%w: failed to read response: %w", sttx.ErrTranscribeFailed, err)
	}

	// Surface the raw response at debug so users can see exactly what
	// Deepgram returned — useful for diagnosing schema drift, partial
	// transcripts, or unexpected fields without rerunning with curl.
	d.log.Debug("deepgram response",
		slog.Int("status", resp.StatusCode),
		slog.String("body", string(respBody)),
	)

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf(
			"%w: Deepgram API returned status %d: %s",
			sttx.ErrTranscribeFailed, resp.StatusCode, string(respBody),
		)
	}

	transcript, err := parseDeepgramResponse(respBody)
	if err != nil {
		return "", err
	}

	d.log.Info("transcription complete", slog.Int("result_len", len(transcript)))

	return transcript, nil
}
