package stt

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"time"

	"github.com/partyzanex/a2text/pkg/sttx"
)

const (
	defaultMaxFileSize = 20 << 20 // 20 MB fallback if not set via config
	deepgramAPITimeout = 60 * time.Second
)

// DeepgramTranscriber implements CloudTranscriber using Deepgram API.
type DeepgramTranscriber struct {
	client      *http.Client
	log         *slog.Logger
	audit       AuditLogger
	apiKey      string
	apiURL      string
	model       string
	maxFileSize int64
}

// NewDeepgramTranscriber creates a new DeepgramTranscriber.
// If log is nil, slog.Default() is used.
// If apiURL is empty, it defaults to https://api.deepgram.com/v1/listen.
// If maxFileSize <= 0, a 20 MB default is used.
// validateWavPath ensures the given WAV file path is safe to open.
// Checks that the path is not a symlink, is a regular file.
// Primarily used for paths generated by internal recording (os.CreateTemp).
func validateWavPath(wavPath string) error {
	if wavPath == "" {
		return fmt.Errorf("%w: empty wav path", sttx.ErrTranscribeFailed)
	}

	// Ensure path is absolute to prevent path traversal attacks.
	if !filepath.IsAbs(wavPath) {
		return fmt.Errorf("%w: wav path must be absolute", sttx.ErrTranscribeFailed)
	}

	// Use Lstat to detect symlinks without following them.
	fileInfo, err := os.Lstat(wavPath)
	if err != nil {
		return fmt.Errorf("%w: stat wav file: %w", sttx.ErrTranscribeFailed, err)
	}

	// Reject symlinks to prevent symlink-based file inclusion attacks.
	if fileInfo.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("%w: wav path is a symlink", sttx.ErrTranscribeFailed)
	}

	// Ensure it's a regular file, not a directory or device.
	if !fileInfo.Mode().IsRegular() {
		return fmt.Errorf("%w: wav path is not a regular file", sttx.ErrTranscribeFailed)
	}

	// Ensure file has reasonable size (not empty).
	if fileInfo.Size() <= 0 {
		return fmt.Errorf("%w: wav file is empty", sttx.ErrTranscribeFailed)
	}

	// Ensure file has .wav extension.
	if filepath.Ext(wavPath) != ".wav" {
		return fmt.Errorf("%w: wav path must have .wav extension", sttx.ErrTranscribeFailed)
	}

	return nil
}

func NewDeepgramTranscriber(apiKey, apiURL string, maxFileSize int64, log *slog.Logger) *DeepgramTranscriber {
	if log == nil {
		log = slog.Default()
	}

	if apiURL == "" {
		apiURL = "https://api.deepgram.com/v1/listen"
	}

	if maxFileSize <= 0 {
		maxFileSize = defaultMaxFileSize
	}

	return &DeepgramTranscriber{
		apiKey:      apiKey,
		apiURL:      apiURL,
		maxFileSize: maxFileSize,
		client:      &http.Client{Timeout: deepgramAPITimeout},
		log:         log,
		audit:       NoopAuditLogger{},
	}
}

// WithAudit attaches an AuditLogger so every Transcribe call records a
// metadata-only event in the audit trail. Passing nil restores the
// no-op default.
func (d *DeepgramTranscriber) WithAudit(audit AuditLogger) *DeepgramTranscriber {
	if audit == nil {
		audit = NoopAuditLogger{}
	}

	d.audit = audit

	return d
}

// WithModel records the Deepgram model name (e.g. "nova-2") in audit
// events. Deepgram binds the model via apiURL query string; the audit
// label is informational only.
func (d *DeepgramTranscriber) WithModel(model string) *DeepgramTranscriber {
	d.model = model

	return d
}

// Name returns the transcriber name.
func (d *DeepgramTranscriber) Name() string {
	return "deepgram"
}

// buildDeepgramURL appends Deepgram-specific query parameters to apiURL.
func buildDeepgramURL(apiURL, lang string) (string, error) {
	parsedURL, err := url.Parse(apiURL)
	if err != nil {
		return "", fmt.Errorf("deepgram: %w", err)
	}

	query := parsedURL.Query()
	query.Set("model", "nova-2")

	if lang != "" && lang != langAuto {
		query.Set("language", lang)
	}

	parsedURL.RawQuery = query.Encode()

	return parsedURL.String(), nil
}

// parseDeepgramResponse extracts the transcript from a Deepgram JSON response body.
func parseDeepgramResponse(body []byte) (string, error) {
	var result struct {
		Results struct {
			Channels []struct {
				Alternatives []struct {
					Transcript string `json:"transcript"`
				} `json:"alternatives"`
			} `json:"channels"`
		} `json:"results"`
	}
	if err := json.Unmarshal(body, &result); err != nil {
		return "", fmt.Errorf("%w: failed to parse response: %w", sttx.ErrTranscribeFailed, err)
	}

	if len(result.Results.Channels) == 0 || len(result.Results.Channels[0].Alternatives) == 0 {
		return "", fmt.Errorf("%w: no transcription results in response", sttx.ErrTranscribeFailed)
	}

	return result.Results.Channels[0].Alternatives[0].Transcript, nil
}

// Transcribe sends the audio file to Deepgram API for transcription.
func (d *DeepgramTranscriber) Transcribe(ctx context.Context, wavPath, lang string) (string, error) {
	event, finish := d.startAudit(wavPath, lang)
	defer finish()

	text, err := d.transcribeOnce(ctx, wavPath, lang, event)

	classifyOutcome(event, text, err)

	return text, err
}

// classifyOutcome maps the (text, err) result of a cloud STT call to one
// of the AuditOutcome* buckets. Shared between OpenAI and Deepgram so
// the schema stays consistent across providers.
func classifyOutcome(event *AuditEvent, text string, err error) {
	switch {
	case err != nil && event.HTTPStatus == 0:
		event.Outcome = AuditOutcomeNetworkErr
	case err != nil:
		event.Outcome = httpStatusBucket(event.HTTPStatus)
	case text == "":
		event.Outcome = AuditOutcomeEmpty
	default:
		event.Outcome = AuditOutcomeOK
		event.TextLen = len(text)
		event.TextSHA256 = hashString(text)
	}
}

// DetectLanguage returns "auto" since Deepgram API auto-detects language.
func (d *DeepgramTranscriber) DetectLanguage(_ context.Context, _ string) (string, error) {
	return "auto", nil
}

// LoadModel is a no-op — no local model needed for the cloud transcriber.
func (d *DeepgramTranscriber) LoadModel(_ string) error { return nil }

// ReloadModel is a no-op — cloud transcriber doesn't support model reload.
func (d *DeepgramTranscriber) ReloadModel(_ string) error { return nil }

// Close is a no-op — no resources to release.
func (d *DeepgramTranscriber) Close() error { return nil }

// startAudit builds the per-request AuditEvent and returns a finalizer
// that records ElapsedMs and emits the event into the audit log.
func (d *DeepgramTranscriber) startAudit(wavPath, lang string) (event *AuditEvent, finish func()) {
	audioBytes, audioDur, audioHash := captureAudioMetrics(wavPath)

	event = &AuditEvent{
		Timestamp:     time.Now().UTC(),
		Provider:      AuditProviderDeepgram,
		Endpoint:      d.apiURL,
		Model:         d.model,
		Lang:          lang,
		AudioBytes:    audioBytes,
		AudioDuration: audioDur,
		AudioSHA256:   audioHash,
	}

	started := time.Now()

	finish = func() {
		event.ElapsedMs = time.Since(started).Milliseconds()
		d.audit.LogEvent(event)
	}

	return event, finish
}

// transcribeOnce executes a single Deepgram request and returns the
// transcript plus any error. HTTP status and request ID land on the
// passed-in event so the caller can finish the audit row.
func (d *DeepgramTranscriber) transcribeOnce(
	ctx context.Context, wavPath, lang string, event *AuditEvent,
) (text string, err error) {
	if validateErr := validateWavPath(wavPath); validateErr != nil {
		event.Outcome = AuditOutcomeBuildErr

		return "", validateErr
	}

	file, err := os.Open(filepath.Clean(wavPath))
	if err != nil {
		event.Outcome = AuditOutcomeBuildErr

		return "", fmt.Errorf("%w: failed to open audio file: %w", sttx.ErrTranscribeFailed, err)
	}

	defer func() {
		if closeErr := file.Close(); closeErr != nil {
			d.log.Debug("failed to close audio file", slog.String("path", wavPath))
		}
	}()

	if sizeErr := d.validateFileSize(file); sizeErr != nil {
		event.Outcome = AuditOutcomeBuildErr

		return "", sizeErr
	}

	req, err := d.buildRequest(ctx, lang, file)
	if err != nil {
		event.Outcome = AuditOutcomeBuildErr

		return "", err
	}

	var (
		status    int
		requestID string
	)

	text, status, requestID, err = d.executeRequestAudited(req, wavPath, lang)

	event.HTTPStatus = status
	event.RequestID = requestID

	return text, err
}

// validateFileSize checks that the audio file does not exceed the configured limit.
func (d *DeepgramTranscriber) validateFileSize(file *os.File) error {
	info, err := file.Stat()
	if err != nil {
		return fmt.Errorf("%w: stat audio file: %w", sttx.ErrTranscribeFailed, err)
	}

	if info.Size() > d.maxFileSize {
		return fmt.Errorf(
			"%w: audio file %d bytes exceeds limit %d",
			sttx.ErrTranscribeFailed, info.Size(), d.maxFileSize,
		)
	}

	return nil
}

// buildRequest creates an HTTP request for the Deepgram API.
func (d *DeepgramTranscriber) buildRequest(ctx context.Context, lang string, body io.Reader) (*http.Request, error) {
	reqURL, err := buildDeepgramURL(d.apiURL, lang)
	if err != nil {
		return nil, fmt.Errorf("%w: failed to parse API URL: %w", sttx.ErrTranscribeFailed, err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, reqURL, body)
	if err != nil {
		return nil, fmt.Errorf("%w: failed to create request: %w", sttx.ErrTranscribeFailed, err)
	}

	req.Header.Set("Authorization", "Token "+d.apiKey)
	req.Header.Set("Content-Type", "audio/wav")

	return req, nil
}

// executeRequestAudited sends the request, parses the response and
// returns the HTTP status code + request ID needed to populate the
// audit event alongside the transcript.
func (d *DeepgramTranscriber) executeRequestAudited(
	req *http.Request, wavPath, lang string,
) (transcript string, status int, requestID string, err error) {
	d.log.Info("sending request to Deepgram API", slog.String("wav", wavPath), slog.String("lang", lang))

	resp, err := d.client.Do(req)
	if err != nil {
		return "", 0, "", fmt.Errorf("%w: request failed: %w", sttx.ErrTranscribeFailed, err)
	}
	defer func() {
		if closeErr := resp.Body.Close(); closeErr != nil {
			d.log.Debug("failed to close response body")
		}
	}()

	status = resp.StatusCode

	requestID = resp.Header.Get("Dg-Request-Id")
	if requestID == "" {
		requestID = resp.Header.Get("X-Request-Id")
	}

	respBody, readErr := io.ReadAll(io.LimitReader(resp.Body, maxRespBodySize))
	if readErr != nil {
		return "", status, requestID,
			fmt.Errorf("%w: failed to read response: %w", sttx.ErrTranscribeFailed, readErr)
	}

	d.log.Debug("deepgram response",
		slog.Int("status", resp.StatusCode),
		slog.String("body", string(respBody)),
	)

	if resp.StatusCode != http.StatusOK {
		return "", status, requestID, fmt.Errorf(
			"%w: Deepgram API returned status %d: %s",
			sttx.ErrTranscribeFailed, resp.StatusCode, string(respBody),
		)
	}

	transcript, err = parseDeepgramResponse(respBody)
	if err != nil {
		return "", status, requestID, err
	}

	d.log.Info("transcription complete", slog.Int("result_len", len(transcript)))

	return transcript, status, requestID, nil
}
