// Code generated by MockGen. DO NOT EDIT.
// Source: fallback.go
//
// Generated by this command:
//
//	mockgen -write_package_comment=false -package=stt -destination=fallback_mocks_test.go -source=fallback.go STTBackend
//

package stt

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSTTBackend is a mock of STTBackend interface.
type MockSTTBackend struct {
	ctrl     *gomock.Controller
	recorder *MockSTTBackendMockRecorder
	isgomock struct{}
}

// MockSTTBackendMockRecorder is the mock recorder for MockSTTBackend.
type MockSTTBackendMockRecorder struct {
	mock *MockSTTBackend
}

// NewMockSTTBackend creates a new mock instance.
func NewMockSTTBackend(ctrl *gomock.Controller) *MockSTTBackend {
	mock := &MockSTTBackend{ctrl: ctrl}
	mock.recorder = &MockSTTBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSTTBackend) EXPECT() *MockSTTBackendMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSTTBackend) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSTTBackendMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSTTBackend)(nil).Close))
}

// DetectLanguage mocks base method.
func (m *MockSTTBackend) DetectLanguage(ctx context.Context, wavPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetectLanguage", ctx, wavPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetectLanguage indicates an expected call of DetectLanguage.
func (mr *MockSTTBackendMockRecorder) DetectLanguage(ctx, wavPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectLanguage", reflect.TypeOf((*MockSTTBackend)(nil).DetectLanguage), ctx, wavPath)
}

// LoadModel mocks base method.
func (m *MockSTTBackend) LoadModel(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadModel", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadModel indicates an expected call of LoadModel.
func (mr *MockSTTBackendMockRecorder) LoadModel(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadModel", reflect.TypeOf((*MockSTTBackend)(nil).LoadModel), path)
}

// ReloadModel mocks base method.
func (m *MockSTTBackend) ReloadModel(newPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReloadModel", newPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReloadModel indicates an expected call of ReloadModel.
func (mr *MockSTTBackendMockRecorder) ReloadModel(newPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadModel", reflect.TypeOf((*MockSTTBackend)(nil).ReloadModel), newPath)
}

// Transcribe mocks base method.
func (m *MockSTTBackend) Transcribe(ctx context.Context, wavPath, lang string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transcribe", ctx, wavPath, lang)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transcribe indicates an expected call of Transcribe.
func (mr *MockSTTBackendMockRecorder) Transcribe(ctx, wavPath, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transcribe", reflect.TypeOf((*MockSTTBackend)(nil).Transcribe), ctx, wavPath, lang)
}
