// Command gen-keys generates typed constants for every message id in
// the canonical English catalogue (messages/en.toml). The output file
// keys.gen.go lives next to i18n.go and is consumed by callers that
// want compile-time protection against typos:
//
//	i18n.T(i18n.KeyWindowTitle)   // compile error if the const is wrong
//	i18n.T("window.title")         // still works, no compile-time check
//
// Run via:  go generate ./internal/i18n/...
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
)

const (
	sourceCatalogue = "internal/i18n/messages/en.toml"
	outputFile      = "internal/i18n/keys.gen.go"
	outputFileMode  = 0o600
)

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		exit("locate repo root: %v", err)
	}

	src := filepath.Join(repoRoot, sourceCatalogue)

	raw, err := os.ReadFile(src) //nolint:gosec // path is the repo-relative catalogue, not user input
	if err != nil {
		exit("read %s: %v", src, err)
	}

	keys, err := extractKeys(raw)
	if err != nil {
		exit("parse %s: %v", src, err)
	}

	if len(keys) == 0 {
		exit("no message ids found in %s", src)
	}

	sort.Strings(keys)

	formatted, err := render(keys)
	if err != nil {
		exit("render: %v", err)
	}

	out := filepath.Join(repoRoot, outputFile)
	if err := os.WriteFile(out, formatted, outputFileMode); err != nil {
		exit("write %s: %v", out, err)
	}

	fmt.Fprintf(os.Stderr, "gen-keys: wrote %d constants to %s\n", len(keys), out)
}

// extractKeys returns the message ids from the TOML catalogue. The TOML
// file is a flat map of id->string (with optional one/few/many/other
// plural sub-tables); we accept either shape.
func extractKeys(raw []byte) ([]string, error) {
	var doc map[string]any
	if err := toml.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("toml unmarshal: %w", err)
	}

	keys := make([]string, 0, len(doc))
	for k := range doc {
		keys = append(keys, k)
	}

	return keys, nil
}

func render(keys []string) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by internal/i18n/cmd/gen-keys; DO NOT EDIT.\n\n")
	buf.WriteString("package i18n\n\n")
	buf.WriteString("// Message id constants. One per key in messages/en.toml. Using a\n")
	buf.WriteString("// constant instead of a string literal at the call site (i.e.\n")
	buf.WriteString("// i18n.T(i18n.KeyFoo) rather than i18n.T(\"foo\")) gives compile-time\n")
	buf.WriteString("// protection against typos and makes IDE rename-symbol work for\n")
	buf.WriteString("// translation keys.\nconst (\n")

	for _, k := range keys {
		fmt.Fprintf(&buf, "\t%s = %q\n", identFor(k), k)
	}

	buf.WriteString(")\n")

	out, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w", err)
	}

	return out, nil
}

// identFor maps a TOML message id ("card.go_whisper") to a Go
// identifier ("KeyCardGoWhisper"). Dots and underscores delimit words;
// each word is title-cased.
func identFor(key string) string {
	var out strings.Builder

	out.WriteString("Key")

	for _, part := range splitAnyOf(key, "._-") {
		if part == "" {
			continue
		}

		out.WriteString(strings.ToUpper(part[:1]))

		if len(part) > 1 {
			out.WriteString(part[1:])
		}
	}

	return out.String()
}

func splitAnyOf(s, sep string) []string {
	return strings.FieldsFunc(s, func(r rune) bool { return strings.ContainsRune(sep, r) })
}

func findRepoRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getwd: %w", err)
	}

	for dir := cwd; dir != "/" && dir != ""; dir = filepath.Dir(dir) {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
	}

	return "", fmt.Errorf("go.mod not found above %s", cwd)
}

func exit(msg string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-keys: "+msg+"\n", args...)
	os.Exit(1)
}
