// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mocks_test.go -package=inject
//

// Package inject is a generated GoMock package.
package inject

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInputDriver is a mock of InputDriver interface.
type MockInputDriver struct {
	ctrl     *gomock.Controller
	recorder *MockInputDriverMockRecorder
	isgomock struct{}
}

// MockInputDriverMockRecorder is the mock recorder for MockInputDriver.
type MockInputDriverMockRecorder struct {
	mock *MockInputDriver
}

// NewMockInputDriver creates a new mock instance.
func NewMockInputDriver(ctrl *gomock.Controller) *MockInputDriver {
	mock := &MockInputDriver{ctrl: ctrl}
	mock.recorder = &MockInputDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInputDriver) EXPECT() *MockInputDriverMockRecorder {
	return m.recorder
}

// PasteChord mocks base method.
func (m *MockInputDriver) PasteChord(ctx context.Context) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasteChord", ctx)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasteChord indicates an expected call of PasteChord.
func (mr *MockInputDriverMockRecorder) PasteChord(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasteChord", reflect.TypeOf((*MockInputDriver)(nil).PasteChord), ctx)
}
