// Code generated by MockGen. DO NOT EDIT.
// Source: clipboard_autopaste.go
//
// Generated by this command:
//
//	mockgen -package=output -destination=clipboard_autopaste_mocks_test.go -source=clipboard_autopaste.go Autopaster,ClipboardDelivery,ClipboardSnapshotter,ClipboardTypedCopier
//

package output

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAutopaster is a mock of Autopaster interface.
type MockAutopaster struct {
	ctrl     *gomock.Controller
	recorder *MockAutopasterMockRecorder
	isgomock struct{}
}

// MockAutopasterMockRecorder is the mock recorder for MockAutopaster.
type MockAutopasterMockRecorder struct {
	mock *MockAutopaster
}

// NewMockAutopaster creates a new mock instance.
func NewMockAutopaster(ctrl *gomock.Controller) *MockAutopaster {
	mock := &MockAutopaster{ctrl: ctrl}
	mock.recorder = &MockAutopasterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutopaster) EXPECT() *MockAutopasterMockRecorder {
	return m.recorder
}

// Paste mocks base method.
func (m *MockAutopaster) Paste(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Paste", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Paste indicates an expected call of Paste.
func (mr *MockAutopasterMockRecorder) Paste(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paste", reflect.TypeOf((*MockAutopaster)(nil).Paste), ctx)
}

// MockClipboardDelivery is a mock of ClipboardDelivery interface.
type MockClipboardDelivery struct {
	ctrl     *gomock.Controller
	recorder *MockClipboardDeliveryMockRecorder
	isgomock struct{}
}

// MockClipboardDeliveryMockRecorder is the mock recorder for MockClipboardDelivery.
type MockClipboardDeliveryMockRecorder struct {
	mock *MockClipboardDelivery
}

// NewMockClipboardDelivery creates a new mock instance.
func NewMockClipboardDelivery(ctrl *gomock.Controller) *MockClipboardDelivery {
	mock := &MockClipboardDelivery{ctrl: ctrl}
	mock.recorder = &MockClipboardDeliveryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClipboardDelivery) EXPECT() *MockClipboardDeliveryMockRecorder {
	return m.recorder
}

// Deliver mocks base method.
func (m *MockClipboardDelivery) Deliver(ctx context.Context, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deliver", ctx, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deliver indicates an expected call of Deliver.
func (mr *MockClipboardDeliveryMockRecorder) Deliver(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deliver", reflect.TypeOf((*MockClipboardDelivery)(nil).Deliver), ctx, text)
}

// MockClipboardSnapshotter is a mock of ClipboardSnapshotter interface.
type MockClipboardSnapshotter struct {
	ctrl     *gomock.Controller
	recorder *MockClipboardSnapshotterMockRecorder
	isgomock struct{}
}

// MockClipboardSnapshotterMockRecorder is the mock recorder for MockClipboardSnapshotter.
type MockClipboardSnapshotterMockRecorder struct {
	mock *MockClipboardSnapshotter
}

// NewMockClipboardSnapshotter creates a new mock instance.
func NewMockClipboardSnapshotter(ctrl *gomock.Controller) *MockClipboardSnapshotter {
	mock := &MockClipboardSnapshotter{ctrl: ctrl}
	mock.recorder = &MockClipboardSnapshotterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClipboardSnapshotter) EXPECT() *MockClipboardSnapshotterMockRecorder {
	return m.recorder
}

// Snapshot mocks base method.
func (m *MockClipboardSnapshotter) Snapshot(ctx context.Context) (ClipboardSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", ctx)
	ret0, _ := ret[0].(ClipboardSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockClipboardSnapshotterMockRecorder) Snapshot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockClipboardSnapshotter)(nil).Snapshot), ctx)
}

// MockClipboardTypedCopier is a mock of ClipboardTypedCopier interface.
type MockClipboardTypedCopier struct {
	ctrl     *gomock.Controller
	recorder *MockClipboardTypedCopierMockRecorder
	isgomock struct{}
}

// MockClipboardTypedCopierMockRecorder is the mock recorder for MockClipboardTypedCopier.
type MockClipboardTypedCopierMockRecorder struct {
	mock *MockClipboardTypedCopier
}

// NewMockClipboardTypedCopier creates a new mock instance.
func NewMockClipboardTypedCopier(ctrl *gomock.Controller) *MockClipboardTypedCopier {
	mock := &MockClipboardTypedCopier{ctrl: ctrl}
	mock.recorder = &MockClipboardTypedCopierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClipboardTypedCopier) EXPECT() *MockClipboardTypedCopierMockRecorder {
	return m.recorder
}

// CopyTyped mocks base method.
func (m *MockClipboardTypedCopier) CopyTyped(ctx context.Context, mime string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyTyped", ctx, mime, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyTyped indicates an expected call of CopyTyped.
func (mr *MockClipboardTypedCopierMockRecorder) CopyTyped(ctx, mime, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyTyped", reflect.TypeOf((*MockClipboardTypedCopier)(nil).CopyTyped), ctx, mime, data)
}
