// Code generated by MockGen. DO NOT EDIT.
// Source: clipboard.go
//
// Generated by this command:
//
//	mockgen -package=output -destination=clipboard_mocks_test.go -source=clipboard.go ClipboardCopier
//

package output

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClipboardCopier is a mock of ClipboardCopier interface.
type MockClipboardCopier struct {
	ctrl     *gomock.Controller
	recorder *MockClipboardCopierMockRecorder
	isgomock struct{}
}

// MockClipboardCopierMockRecorder is the mock recorder for MockClipboardCopier.
type MockClipboardCopierMockRecorder struct {
	mock *MockClipboardCopier
}

// NewMockClipboardCopier creates a new mock instance.
func NewMockClipboardCopier(ctrl *gomock.Controller) *MockClipboardCopier {
	mock := &MockClipboardCopier{ctrl: ctrl}
	mock.recorder = &MockClipboardCopierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClipboardCopier) EXPECT() *MockClipboardCopierMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockClipboardCopier) Copy(ctx context.Context, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", ctx, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockClipboardCopierMockRecorder) Copy(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockClipboardCopier)(nil).Copy), ctx, text)
}
