// Code generated by MockGen. DO NOT EDIT.
// Source: keyboard_service.go
//
// Generated by this command:
//
//	mockgen -source=keyboard_service.go -destination=keyboard_service_mocks_test.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"

	a2textv1 "github.com/partyzanex/a2text/pkg/proto/a2text/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockHotkeySource is a mock of HotkeySource interface.
type MockHotkeySource struct {
	ctrl     *gomock.Controller
	recorder *MockHotkeySourceMockRecorder
	isgomock struct{}
}

// MockHotkeySourceMockRecorder is the mock recorder for MockHotkeySource.
type MockHotkeySourceMockRecorder struct {
	mock *MockHotkeySource
}

// NewMockHotkeySource creates a new mock instance.
func NewMockHotkeySource(ctrl *gomock.Controller) *MockHotkeySource {
	mock := &MockHotkeySource{ctrl: ctrl}
	mock.recorder = &MockHotkeySourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHotkeySource) EXPECT() *MockHotkeySourceMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockHotkeySource) Subscribe(ctx context.Context) (*a2textv1.InitialState, <-chan *a2textv1.HotkeyEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx)
	ret0, _ := ret[0].(*a2textv1.InitialState)
	ret1, _ := ret[1].(<-chan *a2textv1.HotkeyEvent)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockHotkeySourceMockRecorder) Subscribe(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockHotkeySource)(nil).Subscribe), ctx)
}

// MockInjector is a mock of Injector interface.
type MockInjector struct {
	ctrl     *gomock.Controller
	recorder *MockInjectorMockRecorder
	isgomock struct{}
}

// MockInjectorMockRecorder is the mock recorder for MockInjector.
type MockInjectorMockRecorder struct {
	mock *MockInjector
}

// NewMockInjector creates a new mock instance.
func NewMockInjector(ctrl *gomock.Controller) *MockInjector {
	mock := &MockInjector{ctrl: ctrl}
	mock.recorder = &MockInjectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInjector) EXPECT() *MockInjectorMockRecorder {
	return m.recorder
}

// Inject mocks base method.
func (m *MockInjector) Inject(ctx context.Context, text string) (a2textv1.InjectMode, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inject", ctx, text)
	ret0, _ := ret[0].(a2textv1.InjectMode)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Inject indicates an expected call of Inject.
func (mr *MockInjectorMockRecorder) Inject(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inject", reflect.TypeOf((*MockInjector)(nil).Inject), ctx, text)
}

// MockCycleTrigger is a mock of CycleTrigger interface.
type MockCycleTrigger struct {
	ctrl     *gomock.Controller
	recorder *MockCycleTriggerMockRecorder
	isgomock struct{}
}

// MockCycleTriggerMockRecorder is the mock recorder for MockCycleTrigger.
type MockCycleTriggerMockRecorder struct {
	mock *MockCycleTrigger
}

// NewMockCycleTrigger creates a new mock instance.
func NewMockCycleTrigger(ctrl *gomock.Controller) *MockCycleTrigger {
	mock := &MockCycleTrigger{ctrl: ctrl}
	mock.recorder = &MockCycleTriggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCycleTrigger) EXPECT() *MockCycleTriggerMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockCycleTrigger) Start(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockCycleTriggerMockRecorder) Start(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCycleTrigger)(nil).Start), ctx, token)
}
