// Code generated by MockGen. DO NOT EDIT.
// Source: converter.go
//
// Generated by this command:
//
//	mockgen -write_package_comment=false -package=factory -destination=converter_mocks_test.go -source=converter.go FFmpegInner
//

package factory

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFFmpegInner is a mock of FFmpegInner interface.
type MockFFmpegInner struct {
	ctrl     *gomock.Controller
	recorder *MockFFmpegInnerMockRecorder
	isgomock struct{}
}

// MockFFmpegInnerMockRecorder is the mock recorder for MockFFmpegInner.
type MockFFmpegInnerMockRecorder struct {
	mock *MockFFmpegInner
}

// NewMockFFmpegInner creates a new mock instance.
func NewMockFFmpegInner(ctrl *gomock.Controller) *MockFFmpegInner {
	mock := &MockFFmpegInner{ctrl: ctrl}
	mock.recorder = &MockFFmpegInnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFFmpegInner) EXPECT() *MockFFmpegInnerMockRecorder {
	return m.recorder
}

// ToWAV mocks base method.
func (m *MockFFmpegInner) ToWAV(ctx context.Context, inputPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToWAV", ctx, inputPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToWAV indicates an expected call of ToWAV.
func (mr *MockFFmpegInnerMockRecorder) ToWAV(ctx, inputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToWAV", reflect.TypeOf((*MockFFmpegInner)(nil).ToWAV), ctx, inputPath)
}
