// Code generated by MockGen. DO NOT EDIT.
// Source: output_builder.go
//
// Generated by this command:
//
//	mockgen -write_package_comment=false -package=factory -destination=output_builder_mocks_test.go -source=output_builder.go
//

package factory

import (
	context "context"
	reflect "reflect"

	clipboard "github.com/partyzanex/a2text/pkg/clipboard"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionClipboard is a mock of SessionClipboard interface.
type MockSessionClipboard struct {
	ctrl     *gomock.Controller
	recorder *MockSessionClipboardMockRecorder
	isgomock struct{}
}

// MockSessionClipboardMockRecorder is the mock recorder for MockSessionClipboard.
type MockSessionClipboardMockRecorder struct {
	mock *MockSessionClipboard
}

// NewMockSessionClipboard creates a new mock instance.
func NewMockSessionClipboard(ctrl *gomock.Controller) *MockSessionClipboard {
	mock := &MockSessionClipboard{ctrl: ctrl}
	mock.recorder = &MockSessionClipboardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionClipboard) EXPECT() *MockSessionClipboardMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockSessionClipboard) Copy(ctx context.Context, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", ctx, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockSessionClipboardMockRecorder) Copy(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockSessionClipboard)(nil).Copy), ctx, text)
}

// CopyTyped mocks base method.
func (m *MockSessionClipboard) CopyTyped(ctx context.Context, mime string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyTyped", ctx, mime, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyTyped indicates an expected call of CopyTyped.
func (mr *MockSessionClipboardMockRecorder) CopyTyped(ctx, mime, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyTyped", reflect.TypeOf((*MockSessionClipboard)(nil).CopyTyped), ctx, mime, data)
}

// MockSessionClipboardReader is a mock of SessionClipboardReader interface.
type MockSessionClipboardReader struct {
	ctrl     *gomock.Controller
	recorder *MockSessionClipboardReaderMockRecorder
	isgomock struct{}
}

// MockSessionClipboardReaderMockRecorder is the mock recorder for MockSessionClipboardReader.
type MockSessionClipboardReaderMockRecorder struct {
	mock *MockSessionClipboardReader
}

// NewMockSessionClipboardReader creates a new mock instance.
func NewMockSessionClipboardReader(ctrl *gomock.Controller) *MockSessionClipboardReader {
	mock := &MockSessionClipboardReader{ctrl: ctrl}
	mock.recorder = &MockSessionClipboardReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionClipboardReader) EXPECT() *MockSessionClipboardReaderMockRecorder {
	return m.recorder
}

// Snapshot mocks base method.
func (m *MockSessionClipboardReader) Snapshot(ctx context.Context) (clipboard.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", ctx)
	ret0, _ := ret[0].(clipboard.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockSessionClipboardReaderMockRecorder) Snapshot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockSessionClipboardReader)(nil).Snapshot), ctx)
}

// MockSessionAutopaster is a mock of SessionAutopaster interface.
type MockSessionAutopaster struct {
	ctrl     *gomock.Controller
	recorder *MockSessionAutopasterMockRecorder
	isgomock struct{}
}

// MockSessionAutopasterMockRecorder is the mock recorder for MockSessionAutopaster.
type MockSessionAutopasterMockRecorder struct {
	mock *MockSessionAutopaster
}

// NewMockSessionAutopaster creates a new mock instance.
func NewMockSessionAutopaster(ctrl *gomock.Controller) *MockSessionAutopaster {
	mock := &MockSessionAutopaster{ctrl: ctrl}
	mock.recorder = &MockSessionAutopasterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionAutopaster) EXPECT() *MockSessionAutopasterMockRecorder {
	return m.recorder
}

// Backend mocks base method.
func (m *MockSessionAutopaster) Backend() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backend")
	ret0, _ := ret[0].(string)
	return ret0
}

// Backend indicates an expected call of Backend.
func (mr *MockSessionAutopasterMockRecorder) Backend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backend", reflect.TypeOf((*MockSessionAutopaster)(nil).Backend))
}

// Paste mocks base method.
func (m *MockSessionAutopaster) Paste(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Paste", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Paste indicates an expected call of Paste.
func (mr *MockSessionAutopasterMockRecorder) Paste(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paste", reflect.TypeOf((*MockSessionAutopaster)(nil).Paste), ctx)
}
