// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mocks_test.go -package=voice
//

// Package voice is a generated GoMock package.
package voice

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTranscriber is a mock of Transcriber interface.
type MockTranscriber struct {
	ctrl     *gomock.Controller
	recorder *MockTranscriberMockRecorder
	isgomock struct{}
}

// MockTranscriberMockRecorder is the mock recorder for MockTranscriber.
type MockTranscriberMockRecorder struct {
	mock *MockTranscriber
}

// NewMockTranscriber creates a new mock instance.
func NewMockTranscriber(ctrl *gomock.Controller) *MockTranscriber {
	mock := &MockTranscriber{ctrl: ctrl}
	mock.recorder = &MockTranscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranscriber) EXPECT() *MockTranscriberMockRecorder {
	return m.recorder
}

// Transcribe mocks base method.
func (m *MockTranscriber) Transcribe(ctx context.Context, audioPath, lang string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transcribe", ctx, audioPath, lang)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transcribe indicates an expected call of Transcribe.
func (mr *MockTranscriberMockRecorder) Transcribe(ctx, audioPath, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transcribe", reflect.TypeOf((*MockTranscriber)(nil).Transcribe), ctx, audioPath, lang)
}

// MockConverter is a mock of Converter interface.
type MockConverter struct {
	ctrl     *gomock.Controller
	recorder *MockConverterMockRecorder
	isgomock struct{}
}

// MockConverterMockRecorder is the mock recorder for MockConverter.
type MockConverterMockRecorder struct {
	mock *MockConverter
}

// NewMockConverter creates a new mock instance.
func NewMockConverter(ctrl *gomock.Controller) *MockConverter {
	mock := &MockConverter{ctrl: ctrl}
	mock.recorder = &MockConverterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConverter) EXPECT() *MockConverterMockRecorder {
	return m.recorder
}

// ToWAV mocks base method.
func (m *MockConverter) ToWAV(ctx context.Context, inputPath string) (string, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToWAV", ctx, inputPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ToWAV indicates an expected call of ToWAV.
func (mr *MockConverterMockRecorder) ToWAV(ctx, inputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToWAV", reflect.TypeOf((*MockConverter)(nil).ToWAV), ctx, inputPath)
}

// MockOutput is a mock of Output interface.
type MockOutput struct {
	ctrl     *gomock.Controller
	recorder *MockOutputMockRecorder
	isgomock struct{}
}

// MockOutputMockRecorder is the mock recorder for MockOutput.
type MockOutputMockRecorder struct {
	mock *MockOutput
}

// NewMockOutput creates a new mock instance.
func NewMockOutput(ctrl *gomock.Controller) *MockOutput {
	mock := &MockOutput{ctrl: ctrl}
	mock.recorder = &MockOutputMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutput) EXPECT() *MockOutputMockRecorder {
	return m.recorder
}

// Deliver mocks base method.
func (m *MockOutput) Deliver(ctx context.Context, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deliver", ctx, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deliver indicates an expected call of Deliver.
func (mr *MockOutputMockRecorder) Deliver(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deliver", reflect.TypeOf((*MockOutput)(nil).Deliver), ctx, text)
}

// MockRecorder is a mock of Recorder interface.
type MockRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockRecorderMockRecorder
	isgomock struct{}
}

// MockRecorderMockRecorder is the mock recorder for MockRecorder.
type MockRecorderMockRecorder struct {
	mock *MockRecorder
}

// NewMockRecorder creates a new mock instance.
func NewMockRecorder(ctrl *gomock.Controller) *MockRecorder {
	mock := &MockRecorder{ctrl: ctrl}
	mock.recorder = &MockRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecorder) EXPECT() *MockRecorderMockRecorder {
	return m.recorder
}

// RecordToFile mocks base method.
func (m *MockRecorder) RecordToFile(ctx context.Context, opts RecordOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordToFile", ctx, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordToFile indicates an expected call of RecordToFile.
func (mr *MockRecorderMockRecorder) RecordToFile(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordToFile", reflect.TypeOf((*MockRecorder)(nil).RecordToFile), ctx, opts)
}
