// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/partyzanex/a2text/pkg/capture (interfaces: Recorder)
//
// Generated by this command:
//
//	mockgen -write_package_comment=false -package=voice -destination=recorder_mocks_test.go github.com/partyzanex/a2text/pkg/capture Recorder
//

package voice

import (
	context "context"
	reflect "reflect"

	capture "github.com/partyzanex/a2text/pkg/capture"
	gomock "go.uber.org/mock/gomock"
)

// MockRecorder is a mock of Recorder interface.
type MockRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockRecorderMockRecorder
	isgomock struct{}
}

// MockRecorderMockRecorder is the mock recorder for MockRecorder.
type MockRecorderMockRecorder struct {
	mock *MockRecorder
}

// NewMockRecorder creates a new mock instance.
func NewMockRecorder(ctrl *gomock.Controller) *MockRecorder {
	mock := &MockRecorder{ctrl: ctrl}
	mock.recorder = &MockRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecorder) EXPECT() *MockRecorderMockRecorder {
	return m.recorder
}

// RecordToFile mocks base method.
func (m *MockRecorder) RecordToFile(ctx context.Context, opts capture.Options) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordToFile", ctx, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordToFile indicates an expected call of RecordToFile.
func (mr *MockRecorderMockRecorder) RecordToFile(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordToFile", reflect.TypeOf((*MockRecorder)(nil).RecordToFile), ctx, opts)
}
