// Code generated by MockGen. DO NOT EDIT.
// Source: hotkey.go
//
// Generated by this command:
//
//	mockgen -write_package_comment=false -package=voice -destination=voice_mocks_test.go -source=hotkey.go
//

package voice
