// Code generated by MockGen. DO NOT EDIT.
// Source: hotkey.go
//
// Generated by this command:
//
//	mockgen -package=voice -destination=voice_mocks_test.go -source=hotkey.go
//

// Package voice is a generated GoMock package.
package voice

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHotkeyListener is a mock of HotkeyListener interface.
type MockHotkeyListener struct {
	ctrl     *gomock.Controller
	recorder *MockHotkeyListenerMockRecorder
	isgomock struct{}
}

// MockHotkeyListenerMockRecorder is the mock recorder for MockHotkeyListener.
type MockHotkeyListenerMockRecorder struct {
	mock *MockHotkeyListener
}

// NewMockHotkeyListener creates a new mock instance.
func NewMockHotkeyListener(ctrl *gomock.Controller) *MockHotkeyListener {
	mock := &MockHotkeyListener{ctrl: ctrl}
	mock.recorder = &MockHotkeyListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHotkeyListener) EXPECT() *MockHotkeyListenerMockRecorder {
	return m.recorder
}

// Listen mocks base method.
func (m *MockHotkeyListener) Listen(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Listen", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Listen indicates an expected call of Listen.
func (mr *MockHotkeyListenerMockRecorder) Listen(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Listen", reflect.TypeOf((*MockHotkeyListener)(nil).Listen), ctx)
}

// Stop mocks base method.
func (m *MockHotkeyListener) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockHotkeyListenerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockHotkeyListener)(nil).Stop))
}
