// Code generated by MockGen. DO NOT EDIT.
// Source: daemon.go
//
// Generated by this command:
//
//	mockgen -package=cmd -destination=daemon_mocks_test.go -source=daemon.go transcribeCloser
//

// Package cmd is a generated GoMock package.
package daemon

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MocktranscribeCloser is a mock of transcribeCloser interface.
type MocktranscribeCloser struct {
	ctrl     *gomock.Controller
	recorder *MocktranscribeCloserMockRecorder
	isgomock struct{}
}

// MocktranscribeCloserMockRecorder is the mock recorder for MocktranscribeCloser.
type MocktranscribeCloserMockRecorder struct {
	mock *MocktranscribeCloser
}

// NewMocktranscribeCloser creates a new mock instance.
func NewMocktranscribeCloser(ctrl *gomock.Controller) *MocktranscribeCloser {
	mock := &MocktranscribeCloser{ctrl: ctrl}
	mock.recorder = &MocktranscribeCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktranscribeCloser) EXPECT() *MocktranscribeCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MocktranscribeCloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MocktranscribeCloserMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MocktranscribeCloser)(nil).Close))
}
