// Code generated by MockGen. DO NOT EDIT.
// Source: daemon.go
//
// Generated by this command:
//
//	mockgen -write_package_comment=false -package=daemon -destination=daemon_mocks_test.go -source=daemon.go transcribeCloser
//

package daemon

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MocktranscribeCloser is a mock of transcribeCloser interface.
type MocktranscribeCloser struct {
	ctrl     *gomock.Controller
	recorder *MocktranscribeCloserMockRecorder
	isgomock struct{}
}

// MocktranscribeCloserMockRecorder is the mock recorder for MocktranscribeCloser.
type MocktranscribeCloserMockRecorder struct {
	mock *MocktranscribeCloser
}

// NewMocktranscribeCloser creates a new mock instance.
func NewMocktranscribeCloser(ctrl *gomock.Controller) *MocktranscribeCloser {
	mock := &MocktranscribeCloser{ctrl: ctrl}
	mock.recorder = &MocktranscribeCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktranscribeCloser) EXPECT() *MocktranscribeCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MocktranscribeCloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MocktranscribeCloserMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MocktranscribeCloser)(nil).Close))
}

// MockfyneRunner is a mock of fyneRunner interface.
type MockfyneRunner struct {
	ctrl     *gomock.Controller
	recorder *MockfyneRunnerMockRecorder
	isgomock struct{}
}

// MockfyneRunnerMockRecorder is the mock recorder for MockfyneRunner.
type MockfyneRunnerMockRecorder struct {
	mock *MockfyneRunner
}

// NewMockfyneRunner creates a new mock instance.
func NewMockfyneRunner(ctrl *gomock.Controller) *MockfyneRunner {
	mock := &MockfyneRunner{ctrl: ctrl}
	mock.recorder = &MockfyneRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfyneRunner) EXPECT() *MockfyneRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockfyneRunner) Run() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run")
}

// Run indicates an expected call of Run.
func (mr *MockfyneRunnerMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockfyneRunner)(nil).Run))
}

// Stop mocks base method.
func (m *MockfyneRunner) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockfyneRunnerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockfyneRunner)(nil).Stop))
}
