// Code generated by MockGen. DO NOT EDIT.
// Source: depcheck.go
//
// Generated by this command:
//
//	mockgen -package=cmd -destination=depcheck_mocks_test.go -source=depcheck.go PathLookuper
//

// Package cmd is a generated GoMock package.
package daemon

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPathLookuper is a mock of PathLookuper interface.
type MockPathLookuper struct {
	ctrl     *gomock.Controller
	recorder *MockPathLookuperMockRecorder
	isgomock struct{}
}

// MockPathLookuperMockRecorder is the mock recorder for MockPathLookuper.
type MockPathLookuperMockRecorder struct {
	mock *MockPathLookuper
}

// NewMockPathLookuper creates a new mock instance.
func NewMockPathLookuper(ctrl *gomock.Controller) *MockPathLookuper {
	mock := &MockPathLookuper{ctrl: ctrl}
	mock.recorder = &MockPathLookuperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPathLookuper) EXPECT() *MockPathLookuperMockRecorder {
	return m.recorder
}

// LookPath mocks base method.
func (m *MockPathLookuper) LookPath(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookPath", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookPath indicates an expected call of LookPath.
func (mr *MockPathLookuperMockRecorder) LookPath(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookPath", reflect.TypeOf((*MockPathLookuper)(nil).LookPath), name)
}
